Repository hmcts/et-syr-frontend, pull requests merged in 2024-11, with the labels that each got.

#337 RET-3465
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
Labels: ns:et, prd:et, rel:et-syr-pr-337

#343 Fortify Issues
  src/main/definitions/constants.ts
  src/test/unit/auth/auth.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-343

#344 Respondent Name
  src/main/components/form.ts
  src/main/controllers/RespondentNameController.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/respondent-name.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/respondent-name.json
  src/test/unit/components/form.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-344

#350 Check your answers & accessibility
  src/main/controllers/BaseCYAController.ts
  src/main/controllers/CheckYourAnswersContactDetailsController.ts
  src/main/controllers/CheckYourAnswersContestClaimController.ts
  src/main/controllers/CheckYourAnswersEarlyConciliationAndEmployeeDetailsController.ts
  src/main/controllers/CheckYourAnswersEmployersContractClaimController.ts
  src/main/controllers/CheckYourAnswersHearingPreferencesController.ts
  src/main/controllers/CheckYourAnswersPayPensionAndBenefitsController.ts
  src/main/controllers/RespondentContactPhoneNumberController.ts
  src/main/controllers/RespondentContactPreferencesController.ts
  src/main/controllers/RespondentDXAddressController.ts
  src/main/controllers/RespondentPreferredContactNameController.ts
  src/main/resources/locales/cy/translation/check-your-answers-contact-details.json
  src/main/resources/locales/cy/translation/check-your-answers-contest-claim.json
  src/main/resources/locales/cy/translation/check-your-answers-early-conciliation-and-employee-details.json
  src/main/resources/locales/cy/translation/check-your-answers-et3-common.json
  src/main/resources/locales/cy/translation/check-your-answers-hearing-preferences.json
  src/main/resources/locales/cy/translation/check-your-answers-pay-pension-and-benefits.json
  src/main/resources/locales/en/translation/check-your-answers-contact-details.json
  src/main/resources/locales/en/translation/check-your-answers-contest-claim.json
  src/main/resources/locales/en/translation/check-your-answers-early-conciliation-and-employee-details.json
  src/main/resources/locales/en/translation/check-your-answers-et3-common.json
  src/main/resources/locales/en/translation/check-your-answers-hearing-preferences.json
  src/main/resources/locales/en/translation/check-your-answers-pay-pension-and-benefits.json
  src/main/utils/ET3Util.ts
  src/main/views/check-your-answers-contact-details.njk
  src/main/views/check-your-answers-contest-claim.njk
  src/main/views/check-your-answers-early-conciliation-and-employee-details.njk
  src/main/views/check-your-answers-employers-contract-claim.njk
  src/main/views/check-your-answers-hearing-preferences.njk
  src/main/views/check-your-answers-pay-pension-and-benefits.njk
  src/test/unit/controllers/CheckYourAnswersContestClaimController.test.ts
  src/test/unit/controllers/CheckYourAnswersEarlyConciliationAndEmployeeDetailsController.test.ts
  src/test/unit/controllers/CheckYourAnswersEmployersContractClaimController.test.ts
  src/test/unit/controllers/CheckYourAnswersPensionAndBenefitsController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-350

#338 bugfixes
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/CaseListCheckController.ts
  src/main/controllers/CaseNumberCheckController.ts
  src/main/controllers/ClaimSavedController.ts
  src/main/controllers/ClaimantAcasCertificateDetailsController.ts
  src/main/controllers/ClaimantET1FormController.ts
  src/main/controllers/ClaimantET1FormDetailsController.ts
  src/main/controllers/RemoveFileController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentContestClaimReasonController.ts
  src/main/controllers/RespondentSelectPostCodeController.ts
  src/main/controllers/SelfAssignmentCheckController.ts
  src/main/definitions/api/uploadedFile.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/definitions/form.ts
  src/main/definitions/govuk/govukTable.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/helpers/controller/RespondentContestClaimReasonControllerHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/respondent-contest-claim-reason.json
  src/main/resources/locales/cy/translation/respondent-contest-claim.json
  src/main/resources/locales/en/translation/respondent-contest-claim-reason.json
  src/main/resources/locales/en/translation/respondent-contest-claim.json
  src/main/services/CaseService.ts
  src/main/utils/DateUtils.ts
  src/main/utils/DocumentUtils.ts
  src/main/utils/ET3Util.ts
  src/main/utils/ErrorUtils.ts
  src/main/utils/FileUtils.ts
  src/main/utils/ObjectUtils.ts
  src/main/utils/StringUtils.ts
  src/main/views/form/fields/insetFields.njk
  src/main/views/form/fields/table.njk
  src/main/views/respondent-contest-claim-reason.njk
  src/test/unit/controllers/CaseListCheckController.test.ts
  src/test/unit/controllers/ClaimSavedController.test.ts
  src/test/unit/controllers/ClaimantAcasCertificateDetailsController.test.ts
  src/test/unit/controllers/ClaimantET1FormDetailsController.test.ts
  src/test/unit/controllers/RemoveFileController.test.ts
  src/test/unit/controllers/RespondentAddressController.test.ts
  src/test/unit/controllers/RespondentContestClaimController.test.ts
  src/test/unit/controllers/RespondentContestClaimReasonController.test.ts
  src/test/unit/controllers/RespondentSelectPostCodeController.test.ts
  src/test/unit/helpers/controller/RespondentContestClaimReasonControllerHelper.test.ts
  src/test/unit/mocks/mockAxiosResponses.ts
  src/test/unit/mocks/mockDocumentUploadResponse.ts
  src/test/unit/mocks/mockDocuments.ts
  src/test/unit/mocks/mockExpressMulterFile.ts
  src/test/unit/mocks/mockForm.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/utils/DateUtil.test.ts
  src/test/unit/utils/DocumentUtils.test.ts
  src/test/unit/utils/ET3UtilTest.ts
  src/test/unit/utils/ErrorUtils.test.ts
  src/test/unit/utils/FileUtils.test.ts
  src/test/unit/utils/ObjectUtil.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-338

#355 Updates to ET3 reference page
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/self-assignment-form.json
  src/main/resources/locales/en/translation/self-assignment-form.json
  src/main/services/CaseService.ts
  src/test/unit/controllers/SelfAssignmentFormController.test.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-355

#356 RET-5468
  src/main/controllers/ContactTribunalController.ts
  src/main/definitions/constants.ts
  src/main/definitions/contact-tribunal-applications.ts
  src/main/definitions/govuk/govukAccordion.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/contact-tribunal.json
  src/main/resources/locales/en/translation/contact-tribunal.json
  src/main/views/contact-tribunal.njk
  src/test/unit/controllers/ContactTribunalController.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-356

#354 Updates for submitting the case
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/CaseListController.ts
  src/main/controllers/CheckYourAnswersET3Controller.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentResponseLandingController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/definitions/ET3RequestModel.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/modules/oidc/index.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/case-list.json
  src/main/resources/locales/en/translation/common.json
  src/main/services/CaseSelectionService.ts
  src/main/services/CaseService.ts
  src/main/utils/ET3DataModelUtil.ts
  src/main/utils/ET3Util.ts
  src/main/utils/FileUtils.ts
  src/main/utils/NumberUtils.ts
  src/main/utils/ObjectUtils.ts
  src/main/views/case-list.njk
  src/main/views/check-your-answers-et3.njk
  src/main/views/respondent-response-task-list.njk
  src/test/unit/controllers/CaseDetailsController.test.ts
  src/test/unit/controllers/RespondentResponseTaskListController.test.ts
  src/test/unit/controllers/SelfAssignmentFormController.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/services/CaseSelectionService.test.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/utils/ET3DataModelUtil.test.ts
  src/test/unit/utils/ET3UtilTest.ts
  src/test/unit/utils/NumberUtils.test.ts
  src/test/unit/utils/ObjectUtil.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-354

#363 RET-3378
  src/main/helpers/ResponseHubHelper.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-363

#364 RET-4329
  src/main/helpers/ResponseHubHelper.ts
Labels: ns:et, prd:et, rel:et-syr-pr-364

#369 Save as draft & CYA Section 4
  src/main/controllers/ResponseSavedController.ts
  src/main/resources/locales/cy/translation/check-your-answers-et3-common.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/response-saved.json
  src/main/resources/locales/en/translation/check-your-answers-et3-common.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/response-saved.json
  src/main/views/claimant-notice-period.njk
  src/main/views/response-saved.njk
  src/test/unit/controllers/ResponseSavedController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-369

#365 RET-5449
  src/main/controllers/ContactTribunalController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helpers/RouterHelpers.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/helpers/controller/ContactTribunalSelectedHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-amend-my-response.json
  src/main/resources/locales/cy/translation/contact-tribunal-change-my-personal-details.json
  src/main/resources/locales/cy/translation/contact-tribunal-selected.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-amend-my-response.json
  src/main/resources/locales/en/translation/contact-tribunal-change-my-personal-details.json
  src/main/resources/locales/en/translation/contact-tribunal-selected.json
  src/main/views/contact-tribunal-selected.njk
  src/test/unit/controllers/ContactTribunalSelectedController.test.ts
  src/test/unit/helpers/RouterHelper.test.ts
  src/test/unit/views/acas-early-conciliation-certificate.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-365

#371 Submitcase
  bin/stop-redis.sh
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/resources/locales/cy/translation/application-submitted.json
  src/main/resources/locales/en/translation/application-submitted.json
  src/main/utils/ET3DataModelUtil.ts
  src/main/utils/UrlUtils.ts
  src/main/views/application-submitted.njk
  src/test/unit/controllers/AplicationSubmittedController.test.ts
  src/test/unit/utils/UrlUtils.test.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/add-or-update, rel:et-syr-pr-371

#375 CYA Navigation & Contest Claim
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentContestClaimReasonController.ts
  src/main/controllers/RespondentEnterAddressController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/helpers/RouterHelpers.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/helpers/controller/RespondentContactPreferencesControllerHelper.ts
  src/main/helpers/controller/RespondentContestClaimReasonControllerHelper.ts
  src/test/unit/helpers/RouterHelper.test.ts
  src/test/unit/helpers/controller/RespondentContactPreferencesControllerHelperTest.ts
  src/test/unit/helpers/controller/RespondentContestClaimReasonControllerHelper.test.ts
  src/test/unit/mocks/mockApp.ts
Labels: ns:et, prd:et, rel:et-syr-pr-375

#374 BugFixes
  src/main/controllers/RespondentEnterAddressController.ts
  src/main/resources/locales/cy/translation/respondent-enter-address.json
  src/main/resources/locales/en/translation/respondent-enter-address.json
  src/main/utils/ET3DataModelUtil.ts
  src/test/unit/mocks/mockCaseWithId.ts
  src/test/unit/mocks/mockRespondentType.json
  src/test/unit/mocks/mockRespondentType.ts
  src/test/unit/mocks/mockRespondentTypeWithoutCheckedFields.json
  src/test/unit/utils/ET3DataModelUtil.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-374

#376 BugFixes
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/controllers/RemoveFileController.ts
  src/main/controllers/RespondentContestClaimReasonController.ts
  src/main/definitions/constants.ts
  src/main/utils/DocumentUtils.ts
  src/main/utils/FileUtils.ts
  src/main/views/application-submitted.njk
  src/test/unit/controllers/RemoveFileController.test.ts
  src/test/unit/mocks/mockDocumentUploadResponse.ts
  src/test/unit/utils/DocumentUtils.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-376

#379 Response & Response Saved
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/CheckYourAnswersET3Controller.ts
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/controllers/ET3ResponseController.ts
  src/main/controllers/RespondentResponseLandingController.ts
  src/main/definitions/govuk/govukSummaryList.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/resources/locales/cy/translation/application-submitted.json
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/cy/translation/self-assignment-check.json
  src/main/resources/locales/en/translation/application-submitted.json
  src/main/resources/locales/en/translation/case-details.json
  src/main/resources/locales/en/translation/self-assignment-check.json
  src/main/views/application-submitted.njk
  src/main/views/check-your-answers-et3.njk
  src/main/views/components/case-details/case-details-notification-banner.njk
  src/main/views/et3-response.njk
  src/main/views/respondent-response-landing.njk
  src/test/unit/controllers/AplicationSubmittedController.test.ts
  src/test/unit/controllers/ET3ResponseController.test.ts
  src/test/unit/helpers/controller/CheckYourAnswersET3Helper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-379

#385 BugFixes-Case Listing, Completion Status
  package.json
  src/main/controllers/CaseListController.ts
  src/main/resources/locales/en/translation/case-list.json
  src/main/services/CaseSelectionService.ts
  src/main/utils/ET3Util.ts
  src/main/views/case-list.njk
  src/test/unit/controllers/CaseListController.test.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockAxiosResponses.ts
  src/test/unit/mocks/mockCaseApiDataResponse.ts
  src/test/unit/utils/ET3UtilTest.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-385

#391 RET-4320
  package.json
  src/main/controllers/CheckYourAnswersContestClaimController.ts
  src/main/controllers/EmployersContractClaimController.ts
  src/main/controllers/EmployersContractClaimDetailsController.ts
  src/main/controllers/GetCaseDocumentController.ts
  src/main/controllers/RemoveFileController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/definitions/constants.ts
  src/main/definitions/govuk/govukSummaryList.ts
  src/main/definitions/links.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/LanguageHelper.ts
  src/main/helpers/RouterHelpers.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/helpers/controller/EmployersContractClaimDetailsControllerHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/employers-contract-claim-details.json
  src/main/resources/locales/cy/translation/employers-contract-claim.json
  src/main/resources/locales/cy/translation/respondent-response-task-list.json
  src/main/resources/locales/en/translation/employers-contract-claim-details.json
  src/main/resources/locales/en/translation/employers-contract-claim.json
  src/main/resources/locales/en/translation/respondent-response-task-list.json
  src/main/utils/ET3Util.ts
  src/main/utils/StringUtils.ts
  src/main/utils/UrlUtils.ts
  src/main/views/employers-contract-claim-details.njk
  src/test/unit/controllers/CheckYourAnswersContestClaimController.test.ts
  src/test/unit/controllers/EmployersContractClaimController.test.ts
  src/test/unit/controllers/RespondentResponseTaskListController.test.ts
  src/test/unit/definitions/links.test.ts
  src/test/unit/helpers/LanguageHelper.test.ts
  src/test/unit/helpers/RouterHelper.test.ts
  src/test/unit/helpers/controller/CheckYourAnswersET3Helper.test.ts
  src/test/unit/helpers/controller/EmployersContractClaimDetailsControllerHelper.test.ts
  src/test/unit/helpers/controller/RespondentContactPreferencesControllerHelper.test.ts
  src/test/unit/mocks/mockET3HubLinkStatuses.ts
  src/test/unit/test-helpers/test.constants.ts
  src/test/unit/utils/ET3UtilTest.ts
  src/test/unit/utils/StringUtils.test.ts
  src/test/unit/utils/UrlUtils.test.ts
  yarn.lock
Labels: aat/add-or-update, ns:et, prd:et, prod/add-or-update, rel:et-syr-pr-391

#404 Foritfy
  src/main/helpers/RouterHelpers.ts
Labels: ns:et, prd:et, rel:et-syr-pr-404

#405 BugFixes-File_Updates
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/ClaimantET1FormController.ts
  src/main/controllers/EmployersContractClaimController.ts
  src/main/controllers/EmployersContractClaimDetailsController.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentContestClaimReasonController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/cy/translation/employers-contract-claim-details.json
  src/main/resources/locales/en/translation/employers-contract-claim-details.json
  src/main/utils/DocumentUtils.ts
  src/main/utils/ET3DataModelUtil.ts
  src/main/utils/FileUtils.ts
  src/main/utils/NumberUtils.ts
  src/main/views/acas-early-conciliation-certificate.njk
  src/main/views/claimant-et1-form.njk
  src/main/views/respondent-contest-claim-reason.njk
  src/main/views/respondent-response-task-list.njk
  src/test/unit/controllers/EmployersContractClaimDetailsController.test.ts
  src/test/unit/controllers/RespondentContestClaimController.test.ts
  src/test/unit/controllers/RespondentContestClaimReasonController.test.ts
  src/test/unit/controllers/RespondentResponseTaskListController.test.ts
  src/test/unit/utils/DocumentUtils.test.ts
  src/test/unit/utils/FileUtils.test.ts
  src/test/unit/utils/NumberUtils.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-405

#414 Nightly dev
  src/main/controllers/EmployersContractClaimDetailsController.ts
Labels: ns:et, prd:et, rel:et-syr-pr-414

#417 BugFix-RET-4314_4320
  src/main/controllers/CheckYourAnswersContactDetailsController.ts
  src/main/controllers/CheckYourAnswersContestClaimController.ts
  src/main/controllers/CheckYourAnswersEarlyConciliationAndEmployeeDetailsController.ts
  src/main/controllers/CheckYourAnswersEmployersContractClaimController.ts
  src/main/controllers/CheckYourAnswersHearingPreferencesController.ts
  src/main/controllers/CheckYourAnswersPayPensionAndBenefitsController.ts
  src/main/controllers/EmployersContractClaimDetailsController.ts
  src/main/definitions/constants.ts
  src/main/definitions/links.ts
  src/main/resources/locales/cy/translation/employers-contract-claim-details.json
  src/main/resources/locales/en/translation/employers-contract-claim-details.json
  src/test/unit/controllers/CheckYourAnswersContactDetailsController.test.ts
  src/test/unit/controllers/CheckYourAnswersContestClaimController.test.ts
  src/test/unit/controllers/CheckYourAnswersEarlyConciliationAndEmployeeDetailsController.test.ts
  src/test/unit/controllers/CheckYourAnswersHearingPreferencesController.test.ts
  src/test/unit/helpers/controller/RespondentContestClaimReasonControllerHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-417
