Repository hmcts/et-syr-frontend, pull requests merged in 2024-10, with the labels that each got.

#197 Bugfixes
  package.json
  src/main/controllers/SelfAssignmentCheckController.ts
  src/main/views/self-assignment-check.njk
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-197

#195 RET-3465
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/resources/locales/cy/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/en/translation/acas-early-conciliation-certificate.json
  src/test/unit/controllers/AcasEarlyConciliationCertificateController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-195

#196 RET-3466
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/resources/locales/cy/translation/claimant-employment-dates.json
  src/main/resources/locales/en/translation/claimant-employment-dates.json
Labels: ns:et, prd:et, rel:et-syr-pr-196

#204 RET-3479
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/resources/locales/cy/translation/claimant-employment-dates-enter.json
  src/main/resources/locales/en/translation/claimant-employment-dates-enter.json
  src/test/unit/controllers/ClaimantEmploymentDatesEnterController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-204

#206 Update Jenkinsfile_nightly
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-syr-pr-206

#207 RET-3467
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/controllers/ClaimantNoticePeriodController.ts
  src/main/controllers/ClaimantPayDetailsController.ts
  src/main/controllers/IsClaimantEmploymentWithRespondentContinuingController.ts
  src/main/definitions/radios.ts
  src/main/resources/locales/cy/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/cy/translation/claimant-job-title.json
  src/main/resources/locales/cy/translation/claimant-pay-details.json
  src/main/resources/locales/en/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/en/translation/claimant-job-title.json
  src/main/resources/locales/en/translation/claimant-pay-details.json
  src/main/views/acas-early-conciliation-certificate.njk
  src/main/views/claimant-average-weekly-work-hours.njk
  src/main/views/claimant-employment-dates-enter.njk
  src/main/views/claimant-employment-dates.njk
  src/main/views/claimant-job-title.njk
  src/main/views/claimant-notice-period.njk
  src/main/views/claimant-pay-details-enter.njk
  src/main/views/claimant-pay-details.njk
  src/main/views/is-claimant-employment-with-respondent-continuing.njk
  src/test/unit/controllers/ClaimantAverageWeeklyWorkHoursController.test.ts
  src/test/unit/views/acas-early-conciliation-certificate.test.ts
  src/test/unit/views/claimant-average-weekly-work-hours.test.ts
  src/test/unit/views/claimant-employment-dates-enter.test.ts
  src/test/unit/views/claimant-employment-dates.test.ts
  src/test/unit/views/claimant-job-title.test.ts
  src/test/unit/views/claimant-notice-period.test.ts
  src/test/unit/views/claimant-pay-details-enter.test.ts
  src/test/unit/views/claimant-pay-details.test.ts
  src/test/unit/views/is-claimant-employment-with-respondent-continuing.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-207

#198 RET-4329
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/definitions/ET3Request.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/complexTypes/et1Address.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/helpers/ApiFormatter.ts
  src/main/resources/locales/cy/translation/respondent-name.json
  src/main/resources/locales/en/translation/respondent-name.json
  src/main/services/CaseService.ts
  src/main/utils/ET3DataModelUtil.ts
  src/main/utils/ET3Util.ts
  src/test/unit/controllers/RespondentNameController.test.ts
  src/test/unit/mocks/et3Request.json
  src/test/unit/mocks/mockCaseWithId.ts
  src/test/unit/mocks/mockCaseWithIdWithFullRespondentDetails.ts
  src/test/unit/mocks/mockEt3ExpectedRequest.ts
  src/test/unit/mocks/mockEt3Respondent.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/utils/ET3DataModelUtil.test.ts
  src/test/unit/utils/ET3UtilTest.ts
Labels: ns:et, prd:et, rel:et-syr-pr-198

#208 RET-4107
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/claimant-pension-and-benefits.json
  src/main/resources/locales/en/translation/claimant-pension-and-benefits.json
  src/main/views/claimant-pension-and-benefits.njk
  src/test/unit/controllers/ClaimantPensionAndBenefitsController.test.ts
  src/test/unit/views/claimant-pension-and-benefits.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-208

#201 RET-4322 - Final CYA page before submission
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/ET3CYAController.ts
  src/main/controllers/ET3ResponseController.ts
  src/main/definitions/constants.ts
  src/main/definitions/govuk/govukSummaryList.ts
  src/main/helpers/LanguageHelper.ts
  src/main/helpers/RouterHelpers.ts
  src/main/helpers/controller/ET3CYAHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/et3-check-your-answers.json
  src/main/resources/locales/cy/translation/et3-common.json
  src/main/resources/locales/cy/translation/et3-response.json
  src/main/resources/locales/en/translation/et3-check-your-answers.json
  src/main/resources/locales/en/translation/et3-common.json
  src/main/resources/locales/en/translation/et3-response.json
  src/main/views/et3-check-your-answers.njk
  src/main/views/et3-response.njk
  src/test/unit/controllers/ChangeDetailsController.test.ts
  src/test/unit/controllers/ET3CYAController.test.ts
  src/test/unit/helpers/LanguageHelper.test.ts
  src/test/unit/helpers/RouterHelper.test.ts
  src/test/unit/helpers/controller/ET3CYAHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-201

#224 Completed & Response Saved Screens
  src/main/assets/js/go-back.ts
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/controllers/ResponseSavedController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/application-submitted.json
  src/main/resources/locales/cy/translation/response-saved.json
  src/main/resources/locales/en/translation/application-submitted.json
  src/main/resources/locales/en/translation/response-saved.json
  src/main/views/application-submitted.njk
  src/main/views/response-saved.njk
  src/test/unit/controllers/AplicationSubmittedController.test.ts
  src/test/unit/controllers/ResponseSavedController.test.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/add-or-update, rel:et-syr-pr-224

#230 RET-4318
  src/main/controllers/EmployersContractClaimController.ts
  src/main/definitions/constants.ts
  src/main/definitions/links.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/employers-contract-claim.json
  src/main/resources/locales/en/translation/employers-contract-claim.json
  src/main/views/employers-contract-claim.njk
  src/test/unit/controllers/EmployersContractClaimController.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/views/employers-contract-claim.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-230

#235 Fix CVE
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-syr-pr-235

#233 Update ValidationErrors
  src/main/definitions/constants.ts
  src/main/validators/validator.ts
  src/test/unit/validators/validator.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-233

#236 RET-3468
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/resources/locales/cy/translation/claimant-job-title.json
  src/main/resources/locales/en/translation/claimant-job-title.json
  src/main/validators/validator.ts
  src/test/unit/controllers/ClaimantJobTitleController.test.ts
  src/test/unit/validators/validator.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-236

#244 RET-3469
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/resources/locales/cy/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/cy/translation/claimant-job-title.json
  src/main/resources/locales/en/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/en/translation/claimant-job-title.json
  src/main/validators/validator.ts
  src/test/unit/controllers/ClaimantAverageWeeklyWorkHoursController.test.ts
  src/test/unit/validators/validator.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-244

#247 ECC CYA screen
  src/main/controllers/CheckYourAnswersEmployersContractClaimController.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/check-your-answers-employers-contract-claim.json
  src/main/resources/locales/cy/translation/check-your-answers-et3-common.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/check-your-answers-employers-contract-claim.json
  src/main/resources/locales/en/translation/check-your-answers-et3-common.json
  src/main/resources/locales/en/translation/common.json
  src/main/views/check-your-answers-employers-contract-claim.njk
  src/main/views/check-your-answers-et3.njk
  src/test/unit/controllers/CheckYourAnswersEmployersContractClaimController.test.ts
  src/test/unit/helpers/controller/CheckYourAnswersET3Helper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-247

#250 Fix Nightly?
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-syr-pr-250

#229 Ret 4329
  src/main/components/form.ts
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/CheckYourAnswersContactDetailsController.ts
  src/main/controllers/CheckYourAnswersContestClaimController.ts
  src/main/controllers/CheckYourAnswersEarlyConciliationAndEmployeeDetailsController.ts
  src/main/controllers/CheckYourAnswersEmployersContractClaimController.ts
  src/main/controllers/CheckYourAnswersHearingPreferencesController.ts
  src/main/controllers/CheckYourAnswersPayPensionAndBenefitsController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/controllers/SelfAssignmentCheckController.ts
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/controllers/TypeOfOrganisationController.ts
  src/main/definitions/ET3Request.ts
  src/main/definitions/ET3RequestModel.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/CaseHelpers.ts
  src/main/helpers/ErrorHelpers.ts
  src/main/helpers/FormHelper.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/modules/helmet/index.ts
  src/main/services/CaseSelectionService.ts
  src/main/services/CaseService.ts
  src/main/utils/ET3DataModelUtil.ts
  src/main/utils/ET3Util.ts
  src/main/views/form/main/template.njk
  src/test/unit/controllers/CaseDetailsController.test.ts
  src/test/unit/controllers/CheckYourAnswersContactDetailsController.test.ts
  src/test/unit/controllers/CheckYourAnswersContestClaimController.test.ts
  src/test/unit/controllers/CheckYourAnswersEarlyConciliationAndEmployeeDetailsController.test.ts
  src/test/unit/controllers/CheckYourAnswersEmployersContractClaimController.test.ts
  src/test/unit/controllers/CheckYourAnswersHearingPreferencesController.test.ts
  src/test/unit/controllers/CheckYourAnswersPensionAndBenefitsController.test.ts
  src/test/unit/controllers/RespondentNameController.test.ts
  src/test/unit/controllers/SelfAssignmentFormController.test.ts
  src/test/unit/controllers/TypeOfOrganisationController.test.ts
  src/test/unit/helpers/ApiFormatter.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/mocks/et3Request.json
  src/test/unit/mocks/mockCaseApiDataResponse.ts
  src/test/unit/mocks/mockCaseWithId.ts
  src/test/unit/mocks/mockEt3ExpectedRequest.ts
  src/test/unit/mocks/mockStaticFunctions.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockUserCaseWithDecisionsAndJudgments.ts
  src/test/unit/services/CaseService.test.ts
  src/test/unit/utils/ET3DataModelUtil.test.ts
  src/test/unit/utils/ET3UtilTest.ts
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-syr-pr-229

#260 Add Fortify Scanning to et-syr
  Jenkinsfile_nightly
  src/test/java/config/fortify-client.properties
Labels: ns:et, prd:et, rel:et-syr-pr-260

#254 Updates to claimant pay pension and benefits
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/definitions/constants.ts
  src/main/helpers/CaseHelpers.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/resources/locales/cy/translation/claimant-pension-and-benefits.json
  src/main/resources/locales/en/translation/claimant-pension-and-benefits.json
  src/main/services/CaseSelectionService.ts
  src/main/utils/ET3Util.ts
  src/main/validators/validator.ts
  src/main/views/claimant-pension-and-benefits.njk
  src/test/unit/controllers/ClaimantPensionAndBenefitsController.test.ts
  src/test/unit/helpers/CaseHelpers.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/validators/validator.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-254

#253 RET-3465
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/controllers/IsClaimantEmploymentWithRespondentContinuingController.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/resources/locales/cy/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/cy/translation/check-your-answers-et3-common.json
  src/main/resources/locales/cy/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/cy/translation/claimant-employment-dates-enter.json
  src/main/resources/locales/cy/translation/claimant-employment-dates.json
  src/main/resources/locales/cy/translation/claimant-job-title.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/is-claimant-employment-with-respondent-continuing.json
  src/main/resources/locales/en/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/en/translation/check-your-answers-et3-common.json
  src/main/resources/locales/en/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/en/translation/claimant-employment-dates-enter.json
  src/main/resources/locales/en/translation/claimant-employment-dates.json
  src/main/resources/locales/en/translation/claimant-job-title.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/is-claimant-employment-with-respondent-continuing.json
  src/main/views/claimant-average-weekly-work-hours.njk
  src/main/views/claimant-employment-dates.njk
  src/main/views/claimant-job-title.njk
  src/main/views/et3-response.njk
  src/test/unit/controllers/AcasEarlyConciliationCertificateController.test.ts
  src/test/unit/controllers/ClaimantAverageWeeklyWorkHoursController.test.ts
  src/test/unit/controllers/ClaimantEmploymentDatesController.test.ts
  src/test/unit/controllers/ClaimantEmploymentDatesEnterController.test.ts
  src/test/unit/controllers/ClaimantJobTitleController.test.ts
  src/test/unit/controllers/IsClaimantEmploymentWithRespondentContinuingController.test.ts
  src/test/unit/helpers/controller/CheckYourAnswersET3Helper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-253

#269 RET-5353
  src/main/components/form.ts
  src/main/controllers/SelfAssignmentCheckController.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/cy/translation/self-assignment-check.json
  src/main/resources/locales/en/translation/self-assignment-check.json
  src/main/services/AxiosErrorAdapter.ts
  src/main/views/form/main/template.njk
  src/test/unit/components/form.test.ts
  src/test/unit/controllers/SelfAssignmentCheckController.test.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-269

#274 RET-3479
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/definitions/constants.ts
  src/main/helpers/controller/ClaimantEmploymentDatesEnterHelper.ts
  src/main/resources/locales/cy/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/cy/translation/claimant-employment-dates-enter.json
  src/main/resources/locales/cy/translation/claimant-employment-dates.json
  src/main/resources/locales/en/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/en/translation/claimant-employment-dates-enter.json
  src/main/resources/locales/en/translation/claimant-employment-dates.json
  src/main/utils/ErrorUtils.ts
  src/test/unit/controllers/AcasEarlyConciliationCertificateController.test.ts
  src/test/unit/controllers/ClaimantEmploymentDatesController.test.ts
  src/test/unit/controllers/ClaimantEmploymentDatesEnterController.test.ts
  src/test/unit/views/acas-early-conciliation-certificate.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-274

#276 RET-5353
  src/main/controllers/ChecklistController.ts
  src/main/controllers/HomeController.ts
  src/main/controllers/SelfAssignmentCheckController.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/checklist.json
  src/main/resources/locales/cy/translation/self-assignment-check.json
  src/main/resources/locales/en/translation/checklist.json
  src/main/resources/locales/en/translation/self-assignment-check.json
  src/main/views/checklist.njk
  src/main/views/home.njk
  src/main/views/self-assignment-check.njk
  src/test/unit/controllers/ChecklistController.test.ts
  src/test/unit/controllers/HomeController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-276

#275 RET-3465
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/controllers/ClaimantNoticePeriodController.ts
  src/main/controllers/ClaimantPayDetailsController.ts
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/controllers/EmployersContractClaimDetailsController.ts
  src/main/controllers/IsClaimantEmploymentWithRespondentContinuingController.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/resources/locales/cy/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/cy/translation/claimant-job-title.json
  src/main/resources/locales/cy/translation/claimant-notice-period.json
  src/main/resources/locales/cy/translation/claimant-pay-details-enter.json
  src/main/resources/locales/cy/translation/claimant-pay-details.json
  src/main/resources/locales/cy/translation/claimant-pension-and-benefits.json
  src/main/resources/locales/cy/translation/is-claimant-employment-with-respondent-continuing.json
  src/main/resources/locales/en/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/en/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/en/translation/claimant-employment-dates.json
  src/main/resources/locales/en/translation/claimant-job-title.json
  src/main/resources/locales/en/translation/claimant-notice-period.json
  src/main/resources/locales/en/translation/claimant-pay-details-enter.json
  src/main/resources/locales/en/translation/claimant-pay-details.json
  src/main/resources/locales/en/translation/claimant-pension-and-benefits.json
  src/main/resources/locales/en/translation/is-claimant-employment-with-respondent-continuing.json
  src/main/validators/validator.ts
  src/main/views/claimant-notice-period.njk
  src/main/views/claimant-pay-details.njk
  src/test/unit/controllers/AcasEarlyConciliationCertificateController.test.ts
  src/test/unit/controllers/ClaimantAverageWeeklyWorkHoursController.test.ts
  src/test/unit/controllers/ClaimantJobTitleController.test.ts
  src/test/unit/controllers/ClaimantNoticePeriodController.test.ts
  src/test/unit/controllers/ClaimantPayDetailsController.test.ts
  src/test/unit/controllers/ClaimantPayDetailsEnterController.test.ts
  src/test/unit/controllers/ClaimantPensionAndBenefitsController.test.ts
  src/test/unit/controllers/IsClaimantEmploymentWithRespondentContinuingController.test.ts
  src/test/unit/validators/validator.test.ts
  src/test/unit/views/claimant-employment-dates.test.ts
  src/test/unit/views/claimant-pay-details-enter.test.ts
  src/test/unit/views/claimant-pay-details.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-275

#281 Clear Selection
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/controllers/ClaimantNoticePeriodController.ts
  src/main/controllers/ClaimantPayDetailsController.ts
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/controllers/IsClaimantEmploymentWithRespondentContinuingController.ts
  src/main/helpers/RouterHelpers.ts
  src/main/resources/locales/cy/translation/claimant-pension-and-benefits.json
  src/main/resources/locales/en/translation/claimant-pension-and-benefits.json
  src/main/views/form/fields/clearSelection.njk
  src/test/unit/controllers/AcasEarlyConciliationCertificateController.test.ts
  src/test/unit/controllers/ClaimantAverageWeeklyWorkHoursController.test.ts
  src/test/unit/controllers/ClaimantEmploymentDatesController.test.ts
  src/test/unit/controllers/ClaimantJobTitleController.test.ts
  src/test/unit/controllers/ClaimantNoticePeriodController.test.ts
  src/test/unit/controllers/ClaimantPayDetailsController.test.ts
  src/test/unit/controllers/ClaimantPayDetailsEnterController.test.ts
  src/test/unit/controllers/ClaimantPensionAndBenefitsController.test.ts
  src/test/unit/controllers/IsClaimantEmploymentWithRespondentContinuingController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-281

#290 RET-3465
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/resources/locales/cy/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/cy/translation/claimant-pension-and-benefits.json
  src/main/resources/locales/en/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/en/translation/claimant-pension-and-benefits.json
  src/main/views/claimant-employment-dates.njk
Labels: ns:et, prd:et, rel:et-syr-pr-290

#282 RET-4329
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/ClaimantAcasCertificateDetailsController.ts
  src/main/controllers/ClaimantET1FormController.ts
  src/main/controllers/ClaimantET1FormDetailsController.ts
  src/main/controllers/ET1FormViewController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/complexTypes/documentTypeItem.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/claimant-acas-certificate-details.json
  src/main/resources/locales/cy/translation/claimant-et1-form-details.json
  src/main/resources/locales/cy/translation/claimant-et1-form.json
  src/main/resources/locales/en/translation/claimant-acas-certificate-details.json
  src/main/resources/locales/en/translation/claimant-et1-form-details.json
  src/main/resources/locales/en/translation/claimant-et1-form.json
  src/main/utils/DateUtil.ts
  src/main/utils/DocumentUtils.ts
  src/main/utils/ET3Util.ts
  src/main/utils/NumberUtils.ts
  src/main/views/claimant-acas-certificate-details.njk
  src/main/views/claimant-et1-form-details.njk
  src/main/views/claimant-et1-form.njk
  src/test/unit/controllers/ClaimantET1FormController.test.ts
  src/test/unit/controllers/ET1FormViewController.test.ts
  src/test/unit/mocks/mockDocuments.ts
  src/test/unit/utils/DateUtil.test.ts
  src/test/unit/utils/DocumentUtils.test.ts
  src/test/unit/utils/NumberUtils.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-282

#297 Sections 2 & 3
  src/main/controllers/CheckYourAnswersET3Controller.ts
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/controllers/ClaimantNoticePeriodController.ts
  src/main/controllers/ClaimantPayDetailsController.ts
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/controllers/EmployersContractClaimController.ts
  src/main/controllers/EmployersContractClaimDetailsController.ts
  src/main/controllers/IsClaimantEmploymentWithRespondentContinuingController.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentContestClaimReasonController.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/resources/locales/cy/translation/check-your-answers-et3-common.json
  src/main/resources/locales/cy/translation/claimant-employment-dates.json
  src/main/resources/locales/cy/translation/claimant-pay-details.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/cy/translation/employers-contract-claim-details.json
  src/main/resources/locales/cy/translation/employers-contract-claim.json
  src/main/resources/locales/cy/translation/respondent-contest-claim.json
  src/main/resources/locales/en/translation/check-your-answers-et3-common.json
  src/main/resources/locales/en/translation/claimant-employment-dates.json
  src/main/resources/locales/en/translation/claimant-pay-details.json
  src/main/resources/locales/en/translation/common.json
  src/main/resources/locales/en/translation/employers-contract-claim-details.json
  src/main/resources/locales/en/translation/employers-contract-claim.json
  src/main/resources/locales/en/translation/respondent-contest-claim.json
  src/main/views/check-your-answers-et3.njk
  src/main/views/claimant-job-title.njk
  src/main/views/claimant-pay-details.njk
  src/test/unit/controllers/EmployersContractClaimController.test.ts
  src/test/unit/controllers/EmployersContractClaimDetailsController.test.ts
  src/test/unit/controllers/RespondentContestClaimController.test.ts
  src/test/unit/controllers/RespondentContestClaimReasonController.test.ts
  src/test/unit/helpers/controller/CheckYourAnswersET3Helper.test.ts
  src/test/unit/views/claimant-employment-dates.test.ts
  src/test/unit/views/claimant-pay-details.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-297

#301 RET-5423
  src/main/app.ts
  src/main/controllers/CaseListCheckController.ts
  src/main/controllers/CaseListController.ts
  src/main/controllers/CaseNumberCheckController.ts
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/index.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/case-number-check.json
  src/main/resources/locales/en/translation/case-number-check.json
  src/main/services/CaseService.ts
  src/main/views/case-number-check.njk
  src/test/unit/controllers/CaseListCheckController.test.ts
  src/test/unit/controllers/CaseNumberCheckController.test.ts
  src/test/unit/controllers/SelfAssignmentFormController.test.ts
  src/test/unit/mocks/mockAxiosResponses.ts
  src/test/unit/mocks/mockCaseWithId.ts
  src/test/unit/services/CaseService.test.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/add-or-update, rel:et-syr-pr-301

#302 RET-5426
  src/main/components/form.ts
  src/main/controllers/CaseListController.ts
  src/main/controllers/CaseNumberCheckController.ts
  src/main/controllers/HomeController.ts
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/modules/oidc/index.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/resources/locales/cy/translation/self-assignment-check.json
  src/main/resources/locales/cy/translation/self-assignment-form.json
  src/main/resources/locales/en/translation/self-assignment-check.json
  src/main/resources/locales/en/translation/self-assignment-form.json
  src/main/services/AxiosErrorAdapter.ts
  src/main/views/form/main/template.njk
  src/main/views/self-assignment-form.njk
  src/test/unit/components/form.test.ts
  src/test/unit/controllers/CaseNumberCheckController.test.ts
  src/test/unit/controllers/HomeController.test.ts
  src/test/unit/controllers/SelfAssignmentFormController.test.ts
  src/test/unit/mocks/mockAxiosResponses.ts
  src/test/unit/mocks/mockCaseApiDataResponse.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-302

#307 RET-4098
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantPayDetailsController.ts
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/definitions/radios.ts
  src/main/validators/validator.ts
  src/main/views/claimant-average-weekly-work-hours.njk
  src/main/views/claimant-employment-dates.njk
  src/main/views/claimant-notice-period.njk
  src/main/views/claimant-pay-details.njk
  src/test/unit/controllers/ClaimantPayDetailsEnterController.test.ts
  src/test/unit/helpers/ApiFormatter.test.ts
  src/test/unit/mocks/mockCaseWithId.ts
  src/test/unit/mocks/mockUserCaseClaimDetails.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockUserCaseWithDocumentsComplete.ts
  src/test/unit/mocks/mockedApiData.ts
  src/test/unit/validators/validator.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-307

#308 RET-4329
  src/main/controllers/ET1FormViewController.ts
  src/main/controllers/GetCaseDocumentController.ts
  src/main/definitions/constants.ts
  src/main/helpers/DocumentHelpers.ts
  src/main/modules/routes/routes.ts
  src/main/services/CaseService.ts
  src/main/views/claimant-acas-certificate-details.njk
  src/main/views/claimant-et1-form-details.njk
  src/test/unit/controllers/ET1FormViewController.test.ts
  src/test/unit/controllers/GetCaseDocumentController.test.ts
  src/test/unit/helpers/DocumentHelpers.test.ts
  src/test/unit/mocks/documentDetail.json
  src/test/unit/mocks/mockDocumentDetailsResponse.ts
  src/test/unit/mocks/mockDocuments.ts
  src/test/unit/mocks/mockUserCaseWithDocumentsComplete.ts
  src/test/unit/services/CaseService.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-308

#311 BUG_FIXES
  src/main/controllers/CaseDetailsController.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/definition.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/state-sequence.ts
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/en/translation/case-details.json
  src/main/utils/DateUtil.ts
  src/main/views/case-details.njk
  src/main/views/case-list.njk
  src/main/views/components/case-details/case-details-notification-banner.njk
  src/test/unit/helpers/ApiFormatter.test.ts
  src/test/unit/helpers/StateSequence.test.ts
  src/test/unit/mocks/mockRespondentET3Model.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
  src/test/unit/mocks/mockedApiData.ts
  src/test/unit/utils/DateUtil.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-311

#315 Sonar Fixes
  sonar-project.properties
Labels: ns:et, prd:et, rel:et-syr-pr-315

#319 Update to add hint to case number check
  src/main/controllers/CaseNumberCheckController.ts
  src/main/resources/locales/cy/translation/case-number-check.json
  src/main/resources/locales/en/translation/case-number-check.json
Labels: ns:et, prd:et, rel:et-syr-pr-319

#320 Updates for vulnerabilities
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-320

#322 Fortify Issues
  src/main/controllers/CaseNumberCheckController.ts
  src/main/controllers/ChangeDetailsController.ts
  src/main/controllers/SelfAssignmentCheckController.ts
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/definitions/constants.ts
  src/main/helpers/ErrorHelpers.ts
  src/main/helpers/RouterHelpers.ts
  src/main/utils/ET3Util.ts
  src/test/unit/controllers/CaseNumberCheckController.test.ts
  src/test/unit/controllers/ChangeDetailsController.test.ts
  src/test/unit/controllers/SelfAssignmentCheckController.test.ts
  src/test/unit/controllers/SelfAssignmentFormController.test.ts
  src/test/unit/helpers/ErrorHelpers.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-322

#323 BugFixes-DateFields
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/definitions/case.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/utils/DateUtil.ts
  src/main/utils/ET3DataModelUtil.ts
  src/test/unit/utils/DateUtil.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-323

#328 Fortify issues
  src/main/helpers/RouterHelpers.ts
  src/test/unit/helpers/RouterHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-328

#329 Updates to have save as draft functionality.
  src/main/controllers/ClaimSavedController.ts
  src/main/controllers/RespondentSelectPostCodeController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/claim-saved.json
  src/main/resources/locales/cy/translation/respondent-select-postcode.json
  src/main/resources/locales/en/translation/claim-saved.json
  src/main/resources/locales/en/translation/respondent-select-postcode.json
  src/main/utils/ET3Util.ts
  src/main/utils/NumberUtils.ts
  src/main/views/claim-saved.njk
  src/test/unit/controllers/ClaimSavedController.test.ts
  src/test/unit/controllers/RespondentSelectPostCodeController.test.ts
  src/test/unit/helpers/FormHelper.test.ts
  src/test/unit/mocks/mockForm.ts
  src/test/unit/utils/ET3UtilTest.ts
  src/test/unit/utils/NumberUtils.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-329

#331 Fortify issues
  src/main/modules/oidc/index.ts
  src/main/pcq/index.ts
Labels: ns:et, prd:et, rel:et-syr-pr-331

#330 BugFix-ExistingCaseLinks
  src/main/modules/oidc/index.ts
  src/main/services/CacheService.ts
  src/main/views/home.njk
  src/test/unit/services/CacheService.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-330

#332 Updates for login screen
  src/main/modules/oidc/index.ts
  src/main/pcq/index.ts
Labels: ns:et, prd:et, rel:et-syr-pr-332
