Repository hmcts/et-syr-frontend, pull requests merged in 2024-09, with the labels that each got.

#120 RET-5393 Fix compatibility issues with govuk-frontend v5 and swc
  .swcrc
  package.json
  src/main/assets/scss/main.scss
  src/main/modules/nunjucks/index.ts
  webpack.config.js
  webpack/govukFrontend.js
  webpack/hmctsFrontend.js
  yarn-audit-known-issues
  yarn-audit-result
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-120

#126 Fix hmcts-progress-bar
  package.json
  src/main/assets/scss/main.scss
  src/main/modules/nunjucks/index.ts
  src/main/views/components/hmcts-progress-bar/macro.njk
  src/main/views/components/hmcts-progress-bar/template.njk
  src/main/views/home.njk
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-126

#138 Deploy infrastructure to perf and ithc
  Jenkinsfile_CNP
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-138

#121 RET-3444 - Hearing Preferences
  src/main/assets/js/index.js
  src/main/controllers/HearingPreferencesController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentContactPhoneNumberController.ts
  src/main/controllers/RespondentContactPreferencesController.ts
  src/main/controllers/RespondentDXAddressController.ts
  src/main/controllers/RespondentEnterAddressController.ts
  src/main/controllers/RespondentEnterPostCodeController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/controllers/RespondentPreferredContactNameController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/controllers/RespondentSelectPostCodeController.ts
  src/main/controllers/TypeOfOrganisationController.ts
  src/main/definitions/constants.ts
  src/main/helpers/CaseHelpers.ts
  src/main/helpers/ErrorHelpers.ts
  src/main/helpers/FormHelper.ts
  src/main/helpers/RouterHelpers.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/hearing-preferences.json
  src/main/resources/locales/en/translation/hearing-preferences.json
  src/main/views/hearing-preferences.njk
  src/test/unit/controller/HearingPreferenceController.test.ts
  src/test/unit/controller/RespondentAddressController.test.ts
  src/test/unit/controller/RespondentContactPhoneNumberController.test.ts
  src/test/unit/controller/RespondentContactPreferencesController.test.ts
  src/test/unit/controller/RespondentDXAddressController.test.ts
  src/test/unit/controller/RespondentEnterPostCodeController.test.ts
  src/test/unit/controller/RespondentNameController.test.ts
  src/test/unit/controller/RespondentPreferredContactNameController.test.ts
  src/test/unit/controller/RespondentResponseTaskListController.test.ts
  src/test/unit/controller/RespondentSelectPostCodeController.test.ts
  src/test/unit/controller/TypeOfOrganisationController.test.ts
  src/test/unit/helpers/ErrorHelpers.test.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-121

#161 Hearing Preferences - Section 1
  src/main/controllers/RespondentEmployeesController.ts
  src/main/controllers/RespondentSiteEmployeesController.ts
  src/main/controllers/RespondentSitesController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/respondent-employees.json
  src/main/resources/locales/cy/translation/respondent-site-employees.json
  src/main/resources/locales/cy/translation/respondent-sites.json
  src/main/resources/locales/en/translation/respondent-employees.json
  src/main/resources/locales/en/translation/respondent-site-employees.json
  src/main/resources/locales/en/translation/respondent-sites.json
  src/main/views/respondent-employees.njk
  src/main/views/respondent-site-employees.njk
  src/main/views/respondent-sites.njk
  src/test/unit/controller/RespondentEmployeesController.test.ts
  src/test/unit/controller/RespondentSiteEmployeesController.test.ts
  src/test/unit/controller/RespondentSitesController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-161

#162 Hearing Preferences - Respondent Sites
  src/main/controllers/RespondentSitesController.ts
  src/test/unit/controller/RespondentSitesController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-162

#163 Sidebar Screen Fix
  src/main/views/hearing-preferences.njk
  src/main/views/reasonable-adjustments.njk
  src/main/views/respondent-employees.njk
  src/main/views/respondent-site-employees.njk
  src/main/views/respondent-sites.njk
Labels: ns:et, prd:et, rel:et-syr-pr-163

#167 Contest Claim
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentContestClaimReasonController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/respondent-contest-claim-reason.json
  src/main/resources/locales/cy/translation/respondent-contest-claim.json
  src/main/resources/locales/en/translation/respondent-contest-claim-reason.json
  src/main/resources/locales/en/translation/respondent-contest-claim.json
  src/main/views/respondent-contest-claim-reason.njk
  src/main/views/respondent-contest-claim.njk
  src/test/unit/controllers/RespondentContestClaimController.test.ts
  src/test/unit/controllers/RespondentContestClaimReasonController.test.ts
  src/test/unit/controllers/RespondentEmployeesController.test.ts
  src/test/unit/controllers/RespondentSiteEmployeesController.test.ts
  src/test/unit/controllers/RespondentSitesController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-167

#168 RET-3465
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/CheckYourAnswersEarlyConciliationAndEmployeeDetailsController.ts
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/controllers/IsClaimantEmploymentWithRespondentContinuingController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/cy/translation/check-your-answers-early-conciliation-and-employee-details.json
  src/main/resources/locales/cy/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/cy/translation/claimant-employment-dates-enter.json
  src/main/resources/locales/cy/translation/claimant-employment-dates.json
  src/main/resources/locales/cy/translation/claimant-job-title.json
  src/main/resources/locales/cy/translation/is-claimant-employment-with-respondent-continuing.json
  src/main/resources/locales/en/translation/acas-early-conciliation-certificate.json
  src/main/resources/locales/en/translation/check-your-answers-early-conciliation-and-employee-details.json
  src/main/resources/locales/en/translation/claimant-average-weekly-work-hours.json
  src/main/resources/locales/en/translation/claimant-employment-dates-enter.json
  src/main/resources/locales/en/translation/claimant-employment-dates.json
  src/main/resources/locales/en/translation/claimant-job-title.json
  src/main/resources/locales/en/translation/is-claimant-employment-with-respondent-continuing.json
  src/main/views/acas-early-conciliation-certificate.njk
  src/main/views/check-your-answers-early-conciliation-and-employee-details.njk
  src/main/views/claimant-average-weekly-work-hours.njk
  src/main/views/claimant-employment-dates-enter.njk
  src/main/views/claimant-employment-dates.njk
  src/main/views/claimant-job-title.njk
  src/main/views/is-claimant-employment-with-respondent-continuing.njk
  src/test/unit/controllers/AcasEarlyConciliationCertificateController.test.ts
  src/test/unit/controllers/ClaimantAverageWeeklyWorkHoursController.test.ts
  src/test/unit/controllers/ClaimantEmploymentDatesController.test.ts
  src/test/unit/controllers/ClaimantEmploymentDatesEnterController.test.ts
  src/test/unit/controllers/ClaimantJobTitleController.test.ts
  src/test/unit/controllers/IsClaimantEmploymentWithRespondentContinuingController.test.ts
  src/test/unit/views/acas-early-conciliation-certificate.test.ts
  src/test/unit/views/claimant-average-weekly-work-hours.test.ts
  src/test/unit/views/claimant-employment-dates-enter.test.ts
  src/test/unit/views/claimant-employment-dates.test.ts
  src/test/unit/views/claimant-job-title.test.ts
  src/test/unit/views/is-claimant-employment-with-respondent-continuing.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-168

#112 Nightly
  Jenkinsfile_nightly
Labels: ns:et, prd:et, rel:et-syr-pr-112

#177 RET-4330 - ET3 Response
  src/main/assets/scss/main.scss
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/ET3ResponseController.ts
  src/main/definitions/constants.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/cy/translation/et3-response.json
  src/main/resources/locales/en/translation/case-details.json
  src/main/resources/locales/en/translation/et3-response.json
  src/main/views/components/case-details/case-details-notification-banner.njk
  src/main/views/et3-response.njk
  src/test/unit/controllers/ET3ResponseController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-177

#178 RET-4101
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/claimant-pay-details-enter.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/claimant-pay-details-enter.json
  src/main/resources/locales/en/translation/common.json
  src/main/views/claimant-pay-details-enter.njk
  src/test/unit/controllers/ClaimantPayDetailsEnterController.test.ts
  src/test/unit/views/claimant-pay-details-enter.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-178

#194 RET-4106
  src/main/controllers/ClaimantNoticePeriodController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/claimant-notice-period.json
  src/main/resources/locales/en/translation/claimant-notice-period.json
  src/main/views/claimant-notice-period.njk
  src/test/unit/controllers/ClaimantNoticePeriodController.test.ts
  src/test/unit/views/claimant-notice-period.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-194

#187 Bug-Fixes
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/SelfAssignmentCheckController.ts
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/definitions/appRequest.ts
  src/main/resources/locales/cy/translation/case-list.json
  src/main/resources/locales/en/translation/case-list.json
  src/main/services/CaseService.ts
  src/main/views/case-details.njk
  src/main/views/case-list.njk
  src/main/views/components/case-details/case-details-notification-banner.njk
  src/main/views/self-assignment-check.njk
Labels: ns:et, prd:et, rel:et-syr-pr-187
