Repository hmcts/et-syr-frontend, pull requests merged in 2024-12, with the labels that each got.

#418 RET-5368
  src/main/controllers/CaseListController.ts
  src/main/controllers/CheckYourAnswersContestClaimController.ts
  src/main/controllers/CheckYourAnswersET3Controller.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/definitions/constants.ts
  src/main/definitions/links.ts
  src/main/utils/ET3Util.ts
  src/main/views/check-your-answers-et3.njk
  src/main/views/et3-response.njk
  src/test/unit/controllers/CheckYourAnswersContestClaimController.test.ts
  src/test/unit/controllers/RespondentResponseTaskListController.test.ts
  src/test/unit/test-helpers/test.constants.ts
  src/test/unit/utils/ET3UtilTest.ts
Labels: ns:et, prd:et, rel:et-syr-pr-418

#429 Minor bugs
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/controllers/CheckYourAnswersET3Controller.ts
  src/main/controllers/RespondentResponseLandingController.ts
  src/main/resources/locales/cy/translation/check-your-answers-et3.json
  src/main/resources/locales/cy/translation/self-assignment-check.json
  src/main/resources/locales/en/translation/check-your-answers-et3.json
  src/main/resources/locales/en/translation/self-assignment-check.json
  src/main/views/application-submitted.njk
  src/main/views/form/main/template.njk
  src/main/views/self-assignment-check.njk
  src/test/unit/controllers/RespondentResponseLandingController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-429

#422 BugFix
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/CheckYourAnswersET3Controller.ts
  src/main/controllers/EmployersContractClaimController.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/definitions/constants.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/helpers/controller/EmployersContractClaimControllerHelper.ts
  src/main/helpers/controller/RespondentContestClaimControllerHelper.ts
  src/main/resources/locales/cy/translation/check-your-answers-et3.json
  src/main/resources/locales/en/translation/check-your-answers-et3.json
  src/main/utils/CollectionUtils.ts
  src/main/utils/DocumentUtils.ts
  src/main/utils/ET3Util.ts
  src/main/utils/FileUtils.ts
  src/main/utils/RespondentUtils.ts
  src/main/views/check-your-answers-et3.njk
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/helpers/controller/EmployersContractClaimControllerHelper.test.ts
  src/test/unit/helpers/controller/RespondentContestClaimControllerHelper.test.ts
  src/test/unit/utils/CollectionUtils.test.ts
  src/test/unit/utils/DocumentUtils.test.ts
  src/test/unit/utils/RespondentUtils.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-422

#437 Minor Updates
  src/main/controllers/ClaimantAcasCertificateDetailsController.ts
  src/main/controllers/ClaimantET1FormController.ts
  src/main/controllers/ClaimantET1FormDetailsController.ts
  src/main/resources/locales/cy/translation/case-list.json
  src/main/resources/locales/en/translation/case-list.json
  src/main/utils/DateUtils.ts
  src/main/utils/ET3Util.ts
  src/main/views/case-list.njk
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/services/CaseSelectionService.test.ts
  src/test/unit/utils/DateUtil.test.ts
  src/test/unit/utils/ET3UtilTest.ts
Labels: ns:et, prd:et, rel:et-syr-pr-437

#436 RET-4330
  src/main/controllers/CheckYourAnswersContactDetailsController.ts
  src/main/controllers/CheckYourAnswersET3Controller.ts
  src/main/controllers/ET3ResponseController.ts
  src/main/controllers/EmployersContractClaimController.ts
  src/main/controllers/YourResponseFormController.ts
  src/main/definitions/constants.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/employers-contract-claim.json
  src/main/resources/locales/cy/translation/your-response-form.json
  src/main/resources/locales/en/translation/employers-contract-claim.json
  src/main/resources/locales/en/translation/your-response-form.json
  src/main/utils/AddressUtils.ts
  src/main/utils/ET3DataModelUtil.ts
  src/main/utils/ErrorUtils.ts
  src/main/views/your-response-form.njk
  src/test/unit/controllers/YourResponseFormController.test.ts
  src/test/unit/helpers/controller/CheckYourAnswersET3Helper.test.ts
  src/test/unit/mocks/mockCaseWithId.ts
  src/test/unit/mocks/mockRespondentET3Model.ts
  src/test/unit/utils/AddressUtils.test.ts
  src/test/unit/utils/ET3DataModelUtil.test.ts
  src/test/unit/utils/ErrorUtils.test.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/add-or-update, rel:et-syr-pr-436

#442 RET-5468
  src/main/definitions/links.ts
  src/main/helpers/ResponseHubHelper.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/mocks/mockRespondentType.json
  src/test/unit/mocks/mockRespondentTypeWithoutCheckedFields.json
Labels: ns:et, prd:et, rel:et-syr-pr-442

#445 RET-5453
  src/main/resources/locales/cy/translation/contact-tribunal-apply-for-judgment-to-be-reconsidered.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-have-a-decision-considered-afresh.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-postpone-my-hearing.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-restrict-publicity.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-vary-or-revoke-an-order.json
  src/main/resources/locales/cy/translation/contact-tribunal-contact-tribunal.json
  src/main/resources/locales/cy/translation/contact-tribunal-notify-tribunal-applicant-has-not-complied-with-an-order.json
  src/main/resources/locales/cy/translation/contact-tribunal-order-a-witness-to-give-evidence.json
  src/main/resources/locales/cy/translation/contact-tribunal-order-the-applicant-to-do-something.json
  src/main/resources/locales/cy/translation/contact-tribunal-strike-out-all-or-part-of-application.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-for-judgment-to-be-reconsidered.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-amend-my-response.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-have-a-decision-considered-afresh.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-postpone-my-hearing.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-restrict-publicity.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-vary-or-revoke-an-order.json
  src/main/resources/locales/en/translation/contact-tribunal-change-my-personal-details.json
  src/main/resources/locales/en/translation/contact-tribunal-contact-tribunal.json
  src/main/resources/locales/en/translation/contact-tribunal-notify-tribunal-applicant-has-not-complied-with-an-order.json
  src/main/resources/locales/en/translation/contact-tribunal-order-a-witness-to-give-evidence.json
  src/main/resources/locales/en/translation/contact-tribunal-order-the-applicant-to-do-something.json
  src/main/resources/locales/en/translation/contact-tribunal-strike-out-all-or-part-of-application.json
Labels: aat/add-or-update, ns:et, prd:et, prod/add-or-update, rel:et-syr-pr-445

#450 RET-5466
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/contact-tribunal-apply-for-judgment-to-be-reconsidered.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-amend-my-response.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-have-a-decision-considered-afresh.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-postpone-my-hearing.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-restrict-publicity.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-vary-or-revoke-an-order.json
  src/main/resources/locales/cy/translation/contact-tribunal-change-my-personal-details.json
  src/main/resources/locales/cy/translation/contact-tribunal-contact-tribunal.json
  src/main/resources/locales/cy/translation/contact-tribunal-notify-tribunal-applicant-has-not-complied-with-an-order.json
  src/main/resources/locales/cy/translation/contact-tribunal-order-a-witness-to-give-evidence.json
  src/main/resources/locales/cy/translation/contact-tribunal-order-the-applicant-to-do-something.json
  src/main/resources/locales/cy/translation/contact-tribunal-selected.json
  src/main/resources/locales/cy/translation/contact-tribunal-strike-out-all-or-part-of-application.json
  src/main/resources/locales/cy/translation/copy-to-other-party-offline.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-for-judgment-to-be-reconsidered.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-amend-my-response.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-have-a-decision-considered-afresh.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-postpone-my-hearing.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-restrict-publicity.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-vary-or-revoke-an-order.json
  src/main/resources/locales/en/translation/contact-tribunal-change-my-personal-details.json
  src/main/resources/locales/en/translation/contact-tribunal-contact-tribunal.json
  src/main/resources/locales/en/translation/contact-tribunal-notify-tribunal-applicant-has-not-complied-with-an-order.json
  src/main/resources/locales/en/translation/contact-tribunal-order-a-witness-to-give-evidence.json
  src/main/resources/locales/en/translation/contact-tribunal-order-the-applicant-to-do-something.json
  src/main/resources/locales/en/translation/contact-tribunal-selected.json
  src/main/resources/locales/en/translation/contact-tribunal-strike-out-all-or-part-of-application.json
  src/main/resources/locales/en/translation/copy-to-other-party-offline.json
  src/main/views/contact-tribunal-selected.njk
  src/main/views/copy-to-other-party-offline.njk
  src/test/unit/controllers/ContactTribunalSelectedController.test.ts
  src/test/unit/controllers/CopyToOtherPartyController.test.ts
  src/test/unit/helpers/controller/ContactTribunalHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-450

#447 BugFixes
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/RespondentContactPreferencesController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/helpers/ApiFormatter.ts
  src/main/utils/DocumentUtils.ts
  src/main/utils/ET3Util.ts
  src/main/utils/ObjectUtils.ts
  src/main/utils/StringUtils.ts
  src/main/utils/UrlUtils.ts
  src/main/views/claimant-et1-form.njk
  src/test/unit/mocks/mockRespondentET3Model.ts
  src/test/unit/utils/ET3UtilTest.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/add-or-update, rel:et-syr-pr-447

#460 Holding Page
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/HoldingPageController.ts
  src/main/definitions/constants.ts
  src/main/definitions/links.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/helpers/RouterHelpers.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/holding-page.json
  src/main/resources/locales/en/translation/holding-page.json
  src/main/resources/mocks/mockUserCaseWithResponseHubLinks.ts
  src/main/resources/mocks/mockUserCaseWithoutTseApp.ts
  src/main/views/application-submitted.njk
  src/main/views/holding-page.njk
  src/test/unit/controllers/AplicationSubmittedController.test.ts
  src/test/unit/controllers/HoldingPageController.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/helpers/RouterHelper.test.ts
  src/test/unit/mocks/mockRespondentType.json
  src/test/unit/mocks/mockRespondentTypeWithoutCheckedFields.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-460

#455 Applications Claimant Checks
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/test/unit/helpers/controller/ContactTribunalHelper.test.ts
  src/test/unit/mocks/mockUserCase.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/add-or-update, rel:et-syr-pr-455

#464 RET-4330
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/ET3ResponseController.ts
  src/main/controllers/YourResponseFormController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/et3-response.json
  src/main/resources/locales/cy/translation/your-response-form.json
  src/main/resources/locales/en/translation/et3-response.json
  src/main/resources/locales/en/translation/your-response-form.json
  src/main/utils/DocumentUtils.ts
  src/main/views/et3-response.njk
  src/main/views/your-response-form.njk
  src/test/unit/controllers/ET3ResponseController.test.ts
  src/test/unit/controllers/YourResponseFormController.test.ts
  src/test/unit/utils/DocumentUtils.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-464

#466 RET-5513
  src/main/controllers/ContactTribunalCYAController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/definitions/constants.ts
  src/main/helpers/ApplicationHelper.ts
  src/main/helpers/DocumentHelpers.ts
  src/main/helpers/controller/ContactTribunalCYAHelper.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/contact-tribunal-check-your-answers.json
  src/main/resources/locales/en/translation/contact-tribunal-check-your-answers.json
  src/main/views/contact-tribunal-check-your-answers.njk
  src/main/views/contact-tribunal-selected.njk
  src/test/unit/controllers/ContactTribunalCYAController.test.ts
  src/test/unit/helpers/ApplicationHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalCYAHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-466

#467 sidebar
  src/main/resources/locales/cy/translation/holding-page.json
  src/main/resources/locales/en/translation/holding-page.json
  src/main/views/case-details.njk
  src/main/views/components/sidebar/sidebar.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-467

#468 Feature Flag
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/controllers/ContactTribunalController.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/views/case-details.njk
  src/main/views/components/sidebar/sidebar.njk
  src/test/unit/controllers/AplicationSubmittedController.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-468

#481 Sidebar Contact Us
  src/main/resources/locales/cy/translation/sidebar-contact-us.json
  src/main/resources/locales/en/translation/sidebar-contact-us.json
  src/main/views/components/sidebar/sidebar.njk
Labels: ns:et, prd:et, rel:et-syr-pr-481

#482 Sidebar Contact Us
  src/main/resources/locales/cy/translation/sidebar-contact-us.json
  src/main/resources/locales/en/translation/sidebar-contact-us.json
  src/main/views/components/sidebar/sidebar.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-482

#483 RET-5467
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/controllers/YourRequestAndApplicationsController.ts
  src/main/definitions/constants.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/case-details-status.json
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/cy/translation/respondent-response-task-list.json
  src/main/resources/locales/cy/translation/your-request-and-applications.json
  src/main/resources/locales/en/translation/case-details-status.json
  src/main/resources/locales/en/translation/case-details.json
  src/main/resources/locales/en/translation/respondent-response-task-list.json
  src/main/resources/locales/en/translation/your-request-and-applications.json
  src/main/views/your-request-and-applications.njk
  src/test/unit/controllers/YourRequestAndApplicationsController.test.ts
  src/test/unit/helpers/controller/YourRequestAndApplicationsHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-483
