Repository hmcts/et-syr-frontend, pull requests merged in 2024-08, with the labels that each got.

#53 Cookies & Google Analytics to ET3 Form
  src/main/controllers/CookiePreferencesController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/cookie-preferences.json
  src/main/resources/locales/en/translation/cookie-preferences.json
  src/main/views/back-link.njk
  src/main/views/cookie-preferences.njk
  src/main/views/form/main/footer.njk
  src/main/views/form/main/template.njk
  src/test/unit/controller/CookiePreferencesController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-53

#48 RET-5333
  src/main/controllers/HomeController.ts
  src/main/definitions/constants.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/home.json
  src/main/resources/locales/cy/translation/template.json
  src/main/resources/locales/en/translation/home.json
  src/main/resources/locales/en/translation/template.json
  src/main/views/home.njk
  src/test/unit/controller/HomeController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-48

#67 RET-5333
  src/main/resources/locales/cy/translation/home.json
Labels: ns:et, prd:et, rel:et-syr-pr-67

#61 RET-3375
  src/main/controllers/RespondentResponseLandingController.ts
  src/main/controllers/ResponseHubController.ts
  src/main/controllers/helpers/ResponseHubHelper.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/respondent-response-landing.json
  src/main/resources/locales/en/translation/respondent-response-landing.json
  src/main/views/respondent-response-landing.njk
  src/test/unit/controller/RespondentResponseLandingController.test.ts
  src/test/unit/controller/helpers/RespondentHubHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-61

#72 CVEs
  package.json
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-72

#76 RET-3378 - Respondent Task List for ET3
  src/main/controllers/RespondentResponseLandingController.ts
  src/main/controllers/RespondentResponseTaskListController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/respondent-response-task-list.json
  src/main/resources/locales/en/translation/respondent-response-task-list.json
  src/main/views/respondent-response-landing.njk
  src/main/views/respondent-response-task-list.njk
  src/test/unit/controller/RespondentResponseTaskListController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-76

#96 Test- response hub
  src/main/controllers/ResponseHubController.ts
  src/main/modules/oidc/index.ts
  src/main/services/CacheService.ts
  src/test/unit/services/CacheService.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-96

#101 Bug_Correction-New self case assignment
  src/main/controllers/NewSelfAssignmentRequestController.ts
  src/main/controllers/RespondentRepliesController.ts
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/definitions/constants.ts
  src/main/modules/routes/routes.ts
  src/main/views/respondent-replies.njk
  src/test/unit/controller/NewSelfAssignmentRequestControllerTest.ts
  src/test/unit/controller/SelfAssignmentFormController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-101
