Repository hmcts/et-syr-frontend, pull requests merged in 2025-08, with the labels that each got.

#730 Update et1CaseServingPage.ts
  playwrighte2e/pages/et1CaseServingPage.ts
Labels: ns:et, prd:et, rel:et-syr-pr-730

#724 RET-5897
  playwright.config.ts
  playwrighte2e/pages/loginPage.ts
  playwrighte2e/utils/config.ts
  src/main/controllers/ApplicationSubmittedController.ts
  src/main/controllers/AppointLegalRepController.ts
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/ChangeLegalRepresentativeController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/respondent.ts
  src/main/definitions/constants.ts
  src/main/definitions/enums/respondentSolicitorType.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/CaseRoleHelper.ts
  src/main/helpers/RouterHelpers.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/helpers/controller/EmployersContractClaimControllerHelper.ts
  src/main/helpers/controller/RespondentContestClaimControllerHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/appoint-legal-representative.json
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/cy/translation/change-legal-representative.json
  src/main/resources/locales/en/translation/appoint-legal-representative.json
  src/main/resources/locales/en/translation/case-details.json
  src/main/resources/locales/en/translation/change-legal-representative.json
  src/main/services/CaseService.ts
  src/main/utils/DocumentUtils.ts
  src/main/utils/ET3Util.ts
  src/main/utils/ObjectUtils.ts
  src/main/utils/RespondentUtils.ts
  src/main/utils/UrlUtils.ts
  src/main/views/appoint-legal-representative.njk
  src/main/views/case-details.njk
  src/main/views/change-legal-representative.njk
  src/main/views/components/case-details/case-details-notification-banner.njk
  src/main/views/contact-tribunal-selected.njk
  src/test/unit/controllers/ChangeLegalRepresentativeController.test.ts
  src/test/unit/definitions/enums/respondentSolicitorType.test.ts
  src/test/unit/helpers/controller/RespondentContestClaimControllerHelper.test.ts
  src/test/unit/utils/RespondentUtils.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-724

#726 RET-5515
  src/main/controllers/ClaimantPayDetailsController.ts
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentContestClaimReasonController.ts
  src/main/helpers/RouterHelpers.ts
  src/test/unit/controllers/ClaimantEmploymentDatesController.test.ts
  src/test/unit/controllers/ClaimantEmploymentDatesEnterController.test.ts
  src/test/unit/controllers/ClaimantPayDetailsController.test.ts
  src/test/unit/controllers/RespondentContestClaimController.test.ts
  src/test/unit/helpers/RouterHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-726
