Repository hmcts/et-syr-frontend, pull requests merged in 2025-03, with the labels that each got.

#585 RET-5649
  src/main/controllers/ContactTribunalSubmitCompleteController.ts
  src/main/controllers/ContactTribunalSubmitController.ts
  src/main/controllers/RespondToApplicationCompleteController.ts
  src/main/controllers/RespondToApplicationSubmitController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helpers/CaseHelpers.ts
  src/main/helpers/controller/RespondToApplicationCYAHelper.ts
  src/main/services/CaseService.ts
  src/main/views/contact-tribunal-submit-complete.njk
  src/main/views/respond-to-application-complete.njk
  src/test/unit/controllers/ContactTribunalSubmitController.test.ts
  src/test/unit/controllers/RespondToApplicationSubmitController.test.ts
  src/test/unit/helpers/CaseHelpers.test.ts
  src/test/unit/helpers/controller/RespondToApplicationCYAHelper.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockUserCase.ts
  src/test/unit/services/CaseService.test.ts
Labels: aat/add-or-update, ns:et, prd:et, enable_keep_helm, prod/no-changes, rel:et-syr-pr-585

#588 RET-5467
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/ContactTribunalCYAController.ts
  src/main/controllers/RespondToApplicationCYAController.ts
  src/main/controllers/RespondToApplicationSupportingMaterialController.ts
  src/main/helpers/ApplicationHelper.ts
  src/main/helpers/GenericTseApplicationHelper.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/ContactTribunalCYAHelper.ts
  src/main/helpers/controller/RespondToApplicationCYAHelper.ts
  src/main/helpers/controller/RespondToApplicationSupportingMaterialHelper.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/helpers/notification/ApplicationNotificationHelper.ts
  src/main/resources/locales/cy/translation/respond-to-application-check-your-answers.json
  src/main/resources/locales/en/translation/respond-to-application-check-your-answers.json
  src/test/unit/controllers/RespondToApplicationCYAController.test.ts
  src/test/unit/controllers/RespondToApplicationSupportingMaterialController.test.ts
  src/test/unit/helpers/GenericTseApplicationHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalCYAHelper.test.ts
  src/test/unit/helpers/controller/RespondToApplicationCYAHelper.test.ts
  src/test/unit/helpers/controller/RespondToApplicationSupportingMaterialHelper.test.ts
Labels: aat/add-or-update, ns:et, prd:et, enable_keep_helm, prod/no-changes, rel:et-syr-pr-588

#593 RET-5653
  src/main/controllers/AttachmentController.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/helpers/DocumentHelpers.ts
  src/main/helpers/GenericTseApplicationHelper.ts
  src/main/helpers/controller/AttachmentHelper.ts
  src/main/helpers/controller/ClaimantsApplicationsHelper.ts
  src/main/helpers/controller/OtherRespondentsApplicationsHelper.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/helpers/notification/ApplicationNotificationHelper.ts
  src/test/unit/helpers/controller/ApplicationDetailsHelper.test.ts
  src/test/unit/helpers/controller/ClaimantsApplicationsHelper.test.ts
Labels: aat/add-or-update, ns:et, prd:et, enable_keep_helm, prod/no-changes, rel:et-syr-pr-593

#601 RET-5468
  src/main/resources/locales/cy/translation/contact-tribunal.json
  src/main/resources/locales/en/translation/contact-tribunal.json
  src/main/services/CaseService.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/no-changes, rel:et-syr-pr-601

#603 case number ref removed from cya page
  src/main/views/contact-tribunal-check-your-answers.njk
Labels: aat/add-or-update, ns:et, prd:et, prod/no-changes, rel:et-syr-pr-603

#602 RET-5468
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/ContactTribunalSubmitController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/RespondToApplicationSubmitController.ts
  src/main/definitions/constants.ts
  src/main/helpers/ApplicationStateHelper.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/resources/locales/cy/translation/contact-tribunal.json
  src/main/resources/locales/en/translation/contact-tribunal.json
  src/main/services/CaseService.ts
  src/test/unit/controllers/ApplicationDetailsController.test.ts
  src/test/unit/helpers/ApplicationStateHelper.test.ts
  src/test/unit/helpers/controller/YourRequestAndApplicationsHelper.test.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/no-changes, rel:et-syr-pr-602

#606 RET-5654
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/controllers/RespondToApplicationCopyToOtherPartyController.ts
  src/main/controllers/RespondToApplicationSubmitController.ts
  src/main/definitions/applicationList.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/definition.ts
  src/main/helpers/ApplicationStateHelper.ts
  src/main/helpers/controller/CaseDetailsHelper.ts
  src/main/helpers/controller/ClaimantsApplicationsHelper.ts
  src/main/helpers/controller/OtherRespondentsApplicationsHelper.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/resources/locales/cy/translation/your-request-and-applications.json
  src/main/resources/locales/en/translation/your-request-and-applications.json
  src/main/views/your-request-and-applications.njk
  src/test/unit/helpers/ApplicationStateHelper.test.ts
  src/test/unit/helpers/controller/YourRequestAndApplicationsHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-606

#611 RET-5652
  src/main/controllers/CaseDetailsController.ts
  src/main/definitions/constants.ts
  src/main/definitions/contact-tribunal-applications.ts
  src/main/helpers/ApplicationHelper.ts
  src/main/helpers/GenericTseApplicationHelper.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/CaseDetailsHelper.ts
  src/main/helpers/controller/ClaimantsApplicationsHelper.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/application-type.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/application-type.json
  src/test/unit/helpers/ApplicationHelper.test.ts
  src/test/unit/helpers/ApplicationNotificationHelper.test.ts
  src/test/unit/helpers/GenericTseApplicationHelper.test.ts
  src/test/unit/helpers/controller/ApplicationDetailsHelper.test.ts
  src/test/unit/helpers/controller/ClaimantsApplicationsHelper.test.ts
  src/test/unit/helpers/controller/OtherRespondentsApplicationsHelper.test.ts
  src/test/unit/mocks/mockNotificationItem.ts
  src/test/unit/mocks/mockUserCaseComplete.ts
Labels: ns:et, prd:et, rel:et-syr-pr-611

#614 RET-5698
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/helpers/ApplicationStateHelper.ts
  src/main/helpers/GenericTseApplicationHelper.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/RespondToApplicationSubmitHelper.ts
  src/main/helpers/notification/ApplicationNotificationHelper.ts
  src/main/services/CaseService.ts
  src/main/views/application-details.njk
  src/test/unit/controllers/ApplicationDetailsController.test.ts
  src/test/unit/helpers/GenericTseApplicationHelper.test.ts
  src/test/unit/helpers/controller/ApplicationDetailsHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-614

#618 CVE
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-618

#617 RET-5654
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/resources/locales/cy/translation/contact-tribunal.json
  src/main/resources/locales/en/translation/contact-tribunal.json
  src/test/unit/helpers/controller/YourRequestAndApplicationsHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-617

#619 RET-5465
  src/main/resources/locales/cy/translation/copy-to-other-party.json
  src/main/resources/locales/en/translation/copy-to-other-party.json
  src/main/views/copy-to-other-party.njk
Labels: ns:et, prd:et, rel:et-syr-pr-619

#622 RET-5698
  src/main/controllers/ContactTribunalSubmitController.ts
  src/main/helpers/ApplicationStateHelper.ts
  src/main/helpers/controller/CaseDetailsHelper.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/helpers/controller/ContactTribunalSubmitHelper.ts
  src/test/unit/controllers/ContactTribunalSubmitController.test.ts
  src/test/unit/helpers/controller/CaseDetailsHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalSubmitHelper.test.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/no-changes, rel:et-syr-pr-622

#628 RET-5649
  src/main/controllers/ContactTribunalSubmitController.ts
Labels: ns:et, prd:et, rel:et-syr-pr-628

#626 RET-5608
  src/main/helpers/LanguageHelper.ts
  src/main/helpers/RouterHelpers.ts
  src/main/utils/UrlUtils.ts
  src/test/unit/helpers/LanguageHelper.test.ts
  src/test/unit/utils/UrlUtils.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-626

#631 RET-5449
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/helpers/controller/ContactTribunalSelectedControllerHelper.ts
  src/main/resources/locales/cy/translation/contact-tribunal-submit-complete.json
  src/main/resources/locales/en/translation/contact-tribunal-submit-complete.json
  src/main/views/contact-tribunal.njk
Labels: ns:et, prd:et, rel:et-syr-pr-631

#632 RET-5449
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/helpers/controller/OtherRespondentsApplicationsHelper.ts
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/cy/translation/contact-tribunal-selected.json
  src/main/resources/locales/cy/translation/other-respondents-applications.json
  src/main/resources/locales/en/translation/case-details.json
  src/main/resources/locales/en/translation/contact-tribunal-selected.json
  src/main/resources/locales/en/translation/other-respondents-applications.json
  src/main/views/contact-tribunal-selected.njk
Labels: ns:et, prd:et, rel:et-syr-pr-632

#633 RET-5611
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-for-judgment-to-be-reconsidered.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-amend-my-response.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-have-a-decision-considered-afresh.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-postpone-my-hearing.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-restrict-publicity.json
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-vary-or-revoke-an-order.json
  src/main/resources/locales/cy/translation/contact-tribunal-change-my-personal-details.json
  src/main/resources/locales/cy/translation/contact-tribunal-check-your-answers.json
  src/main/resources/locales/cy/translation/contact-tribunal-contact-tribunal.json
  src/main/resources/locales/cy/translation/contact-tribunal-notify-tribunal-applicant-has-not-complied-with-an-order.json
  src/main/resources/locales/cy/translation/contact-tribunal-order-a-witness-to-give-evidence.json
  src/main/resources/locales/cy/translation/contact-tribunal-order-the-applicant-to-do-something.json
  src/main/resources/locales/cy/translation/contact-tribunal-strike-out-all-or-part-of-application.json
  src/main/resources/locales/cy/translation/contact-tribunal-submit-complete.json
  src/main/resources/locales/cy/translation/contact-tribunal.json
  src/main/resources/locales/cy/translation/your-request-and-applications.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-have-a-decision-considered-afresh.json
  src/main/resources/locales/en/translation/contact-tribunal-order-a-witness-to-give-evidence.json
  src/main/resources/locales/en/translation/your-request-and-applications.json
Labels: ns:et, prd:et, rel:et-syr-pr-633

#637 RET-5611
  src/main/controllers/OtherRespondentApplicationsController.ts
  src/main/definitions/constants.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/helpers/controller/CaseDetailsHelper.ts
  src/main/helpers/controller/OtherRespondentApplicationsHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/application-type.json
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/cy/translation/contact-tribunal-selected.json
  src/main/resources/locales/cy/translation/contact-tribunal-strike-out-all-or-part-of-application.json
  src/main/resources/locales/cy/translation/contact-tribunal-submit-complete.json
  src/main/resources/locales/cy/translation/contact-tribunal.json
  src/main/resources/locales/cy/translation/other-respondent-applications.json
  src/main/resources/locales/cy/translation/other-respondents-applications.json
  src/main/resources/locales/cy/translation/respond-to-application-supporting-material.json
  src/main/resources/locales/en/translation/contact-tribunal-selected.json
  src/main/resources/locales/en/translation/other-respondent-applications.json
  src/main/resources/locales/en/translation/respond-to-application-supporting-material.json
  src/test/unit/controllers/OtherRespondentsApplicationsController.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/helpers/controller/OtherRespondentsApplicationsHelper.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-637

#640 RET-5724 - Migrate SYR tests to playwright framework
  .eslintignore
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  package.json
  playwright.config.ts
  playwrighte2e/common/web.action.ts
  playwrighte2e/data/et-england-case-data.json
  playwrighte2e/data/et-scotland-case-data.json
  playwrighte2e/data/test-file/test-doc.pdf
  playwrighte2e/fixtures/common.fixture.ts
  playwrighte2e/fixtures/page.fixture.ts
  playwrighte2e/fixtures/step.fixture.ts
  playwrighte2e/pages/basePage.ts
  playwrighte2e/pages/caseListPage.ts
  playwrighte2e/pages/createCaseThroughApi.ts
  playwrighte2e/pages/et1CaseServingPage.ts
  playwrighte2e/pages/et3LoginPage.ts
  playwrighte2e/pages/et3ProcessPage.ts
  playwrighte2e/pages/loginPage.ts
  playwrighte2e/steps/base.ts
  playwrighte2e/steps/createAndAcceptCase.ts
  playwrighte2e/tests/ET3Journey.test.ts
  playwrighte2e/utils/DateUtilComponent.ts
  playwrighte2e/utils/config.ts
  yarn.lock
Labels: ns:et, prd:et, rel:et-syr-pr-640

#647 typo bug fix
  src/main/definitions/contact-tribunal-applications.ts
Labels: ns:et, prd:et, rel:et-syr-pr-647

#643 RET-5732
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/definitions/constants.ts
  src/test/unit/controllers/ContactTribunalSelectedController.test.ts
  src/test/unit/helpers/controller/ContactTribunalSelectedControllerHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-643

#648 "Reconsider judgement" corrected
  src/main/definitions/contact-tribunal-applications.ts
Labels: ns:et, prd:et, rel:et-syr-pr-648

#649 RET-5737
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/ClaimantsApplicationsController.ts
  src/main/controllers/OtherRespondentApplicationsController.ts
  src/main/controllers/YourRequestAndApplicationsController.ts
  src/test/unit/controllers/ApplicationDetailsController.test.ts
  src/test/unit/controllers/ClaimantsApplicationsController.test.ts
  src/test/unit/controllers/OtherRespondentsApplicationsController.test.ts
  src/test/unit/controllers/YourRequestAndApplicationsController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-649

#655 RET-5740
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/definitions/api/caseApiResponse.ts
  src/main/definitions/case.ts
  src/main/definitions/contact-tribunal-applications.ts
  src/main/helpers/ApiFormatter.ts
  src/main/helpers/ApplicationHelper.ts
  src/main/helpers/GenericTseApplicationHelper.ts
  src/main/helpers/controller/ClaimantsApplicationsHelper.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/contact-tribunal-order-the-applicant-to-do-something.json
  src/main/resources/locales/cy/translation/respond-to-application-complete.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/contact-tribunal-order-the-applicant-to-do-something.json
  src/main/resources/locales/en/translation/respond-to-application-complete.json
  src/test/unit/helpers/ApiFormatter.test.ts
  src/test/unit/helpers/ApplicationHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-655
