Repository hmcts/et-syr-frontend, pull requests merged in 2025-07, with the labels that each got.

#704 RET-5883
  package.json
  src/main/assets/scss/main.scss
  src/main/modules/nunjucks/index.ts
  src/main/views/form/main/footer.njk
  src/main/views/form/main/template.njk
  webpack/govukFrontend.js
  yarn.lock
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-704

#708 RET-5791
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/ContactTribunalController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/definitions/case.ts
  src/main/definitions/complexTypes/representative.ts
  src/main/helpers/ApiFormatter.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/cy/translation/contact-tribunal.json
  src/main/views/components/case-details/case-details-notification-banner.njk
  src/main/views/components/case-details/notifications-respondent-represented.njk
  src/main/views/contact-tribunal.njk
  src/test/unit/helpers/ApiFormatter.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-708

#719 RET-5780
  src/main/resources/locales/cy/translation/contact-tribunal-apply-to-vary-or-revoke-an-order.json
  src/main/resources/locales/cy/translation/contact-tribunal-strike-out-all-or-part-of-application.json
  src/main/resources/locales/cy/translation/copy-to-other-party.json
  src/main/resources/locales/en/translation/contact-tribunal-apply-to-vary-or-revoke-an-order.json
  src/main/resources/locales/en/translation/contact-tribunal-strike-out-all-or-part-of-application.json
  src/main/resources/locales/en/translation/copy-to-other-party.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-719
