Repository hmcts/et-syr-frontend, pull requests merged in 2025-02, with the labels that each got.

#522 RET-5607
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/en/translation/case-details.json
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-522

#525 RET-5548
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/definitions/constants.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/helpers/controller/ContactTribunalSelectedControllerHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/contact-tribunal-selected.json
  src/main/resources/locales/en/translation/contact-tribunal-selected.json
  src/main/views/contact-tribunal-selected.njk
  src/test/unit/helpers/controller/ContactTribunalHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalSelectedControllerHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-525

#515 RET-5556
  src/main/controllers/CaseListController.ts
  src/main/controllers/CaseNumberCheckController.ts
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/definitions/appRequest.ts
  src/main/definitions/constants.ts
  src/main/helpers/RouterHelpers.ts
  src/test/unit/controllers/CaseNumberCheckController.test.ts
  src/test/unit/controllers/SelfAssignmentFormController.test.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/no-changes, rel:et-syr-pr-515

#538 RET-5548
  src/main/controllers/AttachmentController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/ContactTribunalSubmitCompleteController.ts
  src/main/controllers/ContactTribunalSubmitController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/definitions/buttons.ts
  src/main/definitions/case.ts
  src/main/definitions/constants.ts
  src/main/definitions/contact-tribunal-applications.ts
  src/main/definitions/radios.ts
  src/main/helpers/DateHelper.ts
  src/main/helpers/DocumentHelpers.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/ContactTribunalCYAHelper.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/helpers/controller/ContactTribunalSelectedControllerHelper.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/contact-tribunal-check-your-answers.json
  src/main/resources/locales/cy/translation/contact-tribunal-selected.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/contact-tribunal-check-your-answers.json
  src/main/resources/locales/en/translation/contact-tribunal-selected.json
  src/main/views/application-details.njk
  src/main/views/contact-tribunal-submit-complete.njk
  src/main/views/copy-to-other-party.njk
  src/test/unit/controllers/ApplicationDetailsController.test.ts
  src/test/unit/controllers/AttachmentController.test.ts
  src/test/unit/controllers/ContactTribunalSubmitController.test.ts
  src/test/unit/helpers/ApplicationHelper.test.ts
  src/test/unit/helpers/DocumentHelpers.test.ts
  src/test/unit/helpers/controller/ApplicationDetailsHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalCYAHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalSelectedControllerHelper.test.ts
  src/test/unit/helpers/controller/YourRequestAndApplicationsHelper.test.ts
  src/test/unit/mocks/mockGenericTseCollection.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-538

#547 ApplicationHelper
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/CopyToOtherPartyController.ts
  src/main/helpers/ApplicationHelper.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/test/unit/helpers/ApplicationHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-547

#571 RET-5467
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/RespondToApplicationSubmitHelper.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/respond-to-application.json
  src/main/views/application-details.njk
  src/main/views/respond-to-application.njk
  src/test/unit/helpers/controller/ApplicationDetailsHelper.test.ts
  src/test/unit/helpers/controller/OtherRespondentsApplicationsHelper.test.ts
Labels: aat/add-or-update, ns:et, prd:et, enable_keep_helm, prod/no-changes, rel:et-syr-pr-571

#573 RET-5647
  charts/et-syr/Chart.yaml
Labels: ns:et, prd:et, rel:et-syr-pr-573

#574 RET-5467
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/CaseDetailsController.ts
  src/main/definitions/notification/applicationNotification.ts
  src/main/definitions/storeNotification.ts
  src/main/helpers/ApplicationHelper.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/helpers/notification/ApplicationNotificationHelper.ts
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/en/translation/case-details.json
  src/main/views/components/case-details/case-details-notification-banner.njk
  src/test/unit/helpers/ApplicationNotificationHelper.test.ts
Labels: aat/add-or-update, ns:et, prd:et, enable_keep_helm, prod/no-changes, rel:et-syr-pr-574

#567 submit respondent application to et-sya-api endpoint
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/BaseCYAController.ts
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/controllers/ClaimantNoticePeriodController.ts
  src/main/controllers/ClaimantPayDetailsController.ts
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/controllers/ContactTribunalSubmitController.ts
  src/main/controllers/EmployersContractClaimController.ts
  src/main/controllers/HearingPreferencesController.ts
  src/main/controllers/IsClaimantEmploymentWithRespondentContinuingController.ts
  src/main/controllers/ReasonableAdjustmentsController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentContactPhoneNumberController.ts
  src/main/controllers/RespondentContactPreferencesController.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentDXAddressController.ts
  src/main/controllers/RespondentEmployeesController.ts
  src/main/controllers/RespondentEnterAddressController.ts
  src/main/controllers/RespondentEnterPostCodeController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/controllers/RespondentPreferredContactNameController.ts
  src/main/controllers/RespondentSelectPostCodeController.ts
  src/main/controllers/RespondentSiteEmployeesController.ts
  src/main/controllers/RespondentSitesController.ts
  src/main/controllers/TypeOfOrganisationController.ts
  src/main/definitions/constants.ts
  src/main/services/CaseService.ts
  src/test/unit/controllers/ContactTribunalSubmitController.test.ts
  src/test/unit/controllers/RespondentEnterPostCodeController.test.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockUserCase.ts
  src/test/unit/services/CaseService.test.ts
Labels: aat/add-or-update, ns:et, prd:et, prod/no-changes, rel:et-syr-pr-567

#581 RET-5652
  src/main/controllers/CaseDetailsController.ts
  src/main/controllers/ContactTribunalSubmitController.ts
  src/main/definitions/complexTypes/genericTseApplicationTypeItem.ts
  src/main/definitions/links.ts
  src/main/helpers/ResponseHubHelper.ts
  src/main/helpers/controller/CaseDetailsHelper.ts
  src/main/resources/locales/cy/translation/case-details.json
  src/main/resources/locales/en/translation/case-details.json
  src/test/unit/controllers/ContactTribunalSubmitController.test.ts
  src/test/unit/helpers/RespondentHubHelper.test.ts
  src/test/unit/mocks/et3Request.json
  src/test/unit/mocks/mockRespondentType.json
  src/test/unit/mocks/mockRespondentTypeWithoutCheckedFields.json
Labels: ns:et, prd:et, rel:et-syr-pr-581

#580 add response to app logic
  src/main/controllers/RespondToApplicationSubmitController.ts
  src/main/definitions/constants.ts
  src/main/services/CaseService.ts
  src/test/unit/controllers/RespondToApplicationSubmitController.test.ts
Labels: ns:et, prd:et, rel:et-syr-pr-580
