Repository hmcts/et-syr-frontend, pull requests merged in 2025-01, with the labels that each got.

#490 Update mocks
  src/test/unit/helpers/controller/YourRequestAndApplicationsHelper.test.ts
  src/test/unit/mocks/mockApp.ts
  src/test/unit/mocks/mockApplications.ts
  src/test/unit/mocks/mockCaseWithId.ts
  src/test/unit/mocks/mockClaimantTseRequest.ts
  src/test/unit/mocks/mockDocumentApiModel.ts
  src/test/unit/mocks/mockDocumentDetailsResponse.ts
  src/test/unit/mocks/mockDocuments.ts
  src/test/unit/mocks/mockEt1DataModel.ts
  src/test/unit/mocks/mockEt3ExpectedRequest.ts
  src/test/unit/mocks/mockGenericTseCollection.ts
  src/test/unit/mocks/mockRequest.ts
  src/test/unit/mocks/mockTribunalResponse.ts
  src/test/unit/mocks/mockUserCaseWithDecisionsAndJudgments.ts
  src/test/unit/mocks/mockUserCaseWithRespondentDocuments.ts
Labels: ns:et, prd:et, rel:et-syr-pr-490

#486 RET-5467
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/ContactTribunalSelectedController.ts
  src/main/controllers/RespondToApplicationController.ts
  src/main/controllers/YourRequestAndApplicationsController.ts
  src/main/definitions/constants.ts
  src/main/helpers/DocumentHelpers.ts
  src/main/helpers/GenericTseApplicationHelper.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/ContactTribunalCYAHelper.ts
  src/main/helpers/controller/ContactTribunalHelper.ts
  src/main/helpers/controller/RespondToApplicationHelper.ts
  src/main/helpers/controller/YourRequestAndApplicationsHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/application-details.json
  src/main/resources/locales/cy/translation/respond-to-application.json
  src/main/resources/locales/en/translation/application-details.json
  src/main/resources/locales/en/translation/respond-to-application.json
  src/main/views/application-details.njk
  src/main/views/respond-to-application.njk
  src/main/views/your-request-and-applications.njk
  src/test/unit/controllers/ApplicationDetailsController.test.ts
  src/test/unit/controllers/ContactTribunalSelectedController.test.ts
  src/test/unit/controllers/RespondToApplicationController.test.ts
  src/test/unit/helpers/GenericTseApplicationHelper.test.ts
  src/test/unit/helpers/controller/ApplicationDetailsHelper.test.ts
  src/test/unit/helpers/controller/ContactTribunalCYAHelper.test.ts
  src/test/unit/helpers/controller/RespondToApplicationHelper.test.ts
  src/test/unit/helpers/controller/YourRequestAndApplicationsHelper.test.ts
  src/test/unit/validators/validator.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-486

#502 RET-5555
  src/main/helpers/RouterHelpers.ts
  src/main/modules/oidc/index.ts
  src/main/utils/UrlUtils.ts
  src/test/unit/helpers/RouterHelper.test.ts
Labels: aat/add-or-update, ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-502

#507 RET-5559
  src/main/app.ts
  src/main/controllers/CaseNumberCheckController.ts
  src/main/controllers/ReturnToExistingResponseController.ts
  src/main/controllers/SelfAssignmentFormController.ts
  src/main/definitions/constants.ts
  src/main/helpers/RouterHelpers.ts
  src/main/modules/oidc/noSignInRequiredEndpoints.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/return-to-existing-response.json
  src/main/resources/locales/en/translation/return-to-existing-response.json
  src/main/views/home.njk
  src/main/views/return-to-existing-response.njk
  src/test/unit/controllers/CaseNumberCheckController.test.ts
  src/test/unit/controllers/ReturnToExistingResponseController.test.ts
  src/test/unit/controllers/SelfAssignmentFormController.test.ts
Labels: aat/add-or-update, ns:et, prd:et, enable_keep_helm

#510 RET-5567
  src/main/controllers/ReturnToExistingResponseController.ts
Labels: ns:et, prd:et, enable_keep_helm

#509 RET-5467
  src/main/controllers/ApplicationDetailsController.ts
  src/main/controllers/RespondToTribunalController.ts
  src/main/controllers/RespondToTribunalSupportingMaterialController.ts
  src/main/definitions/constants.ts
  src/main/helpers/controller/ApplicationDetailsHelper.ts
  src/main/helpers/controller/RespondToTribunalHelper.ts
  src/main/modules/routes/routes.ts
  src/main/resources/locales/cy/translation/copy-to-other-party-offline.json
  src/main/resources/locales/cy/translation/respond-to-tribunal-supporting-material.json
  src/main/resources/locales/cy/translation/respond-to-tribunal.json
  src/main/resources/locales/en/translation/copy-to-other-party-offline.json
  src/main/resources/locales/en/translation/respond-to-tribunal-supporting-material.json
  src/main/resources/locales/en/translation/respond-to-tribunal.json
  src/main/views/application-details.njk
  src/main/views/copy-to-other-party-offline.njk
  src/main/views/respond-to-tribunal-supporting-material.njk
  src/main/views/respond-to-tribunal.njk
  src/test/unit/controllers/ApplicationDetailsController.test.ts
  src/test/unit/controllers/RespondToTribunalController.test.ts
  src/test/unit/controllers/RespondToTribunalSupportingMaterialController.test.ts
  src/test/unit/helpers/controller/ApplicationDetailsHelper.test.ts
  src/test/unit/helpers/controller/RespondToTribunalHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm

#512 RET-5554 Code Change
  src/main/controllers/ClaimantNoticePeriodController.ts
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/helpers/controller/CheckYourAnswersET3Helper.ts
  src/main/helpers/controller/ClaimantNoticePeriodHelper.ts
  src/main/helpers/controller/ClaimantPensionAndBenefitsHelper.ts
  src/main/resources/locales/cy/translation/check-your-answers-et3-common.json
  src/main/resources/locales/cy/translation/claimant-notice-period.json
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/check-your-answers-et3-common.json
  src/main/resources/locales/en/translation/claimant-notice-period.json
  src/main/resources/locales/en/translation/common.json
  src/main/utils/TranslationUtils.ts
  src/main/views/claimant-notice-period.njk
  src/main/views/claimant-pension-and-benefits.njk
  src/test/unit/helpers/controller/CheckYourAnswersET3Helper.test.ts
  src/test/unit/helpers/controller/ClaimantNoticePeriodHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm

#499 RET-5553
  src/main/controllers/AcasEarlyConciliationCertificateController.ts
  src/main/controllers/BaseCYAController.ts
  src/main/controllers/ClaimantAverageWeeklyWorkHoursController.ts
  src/main/controllers/ClaimantEmploymentDatesController.ts
  src/main/controllers/ClaimantEmploymentDatesEnterController.ts
  src/main/controllers/ClaimantJobTitleController.ts
  src/main/controllers/ClaimantNoticePeriodController.ts
  src/main/controllers/ClaimantPayDetailsController.ts
  src/main/controllers/ClaimantPayDetailsEnterController.ts
  src/main/controllers/ClaimantPensionAndBenefitsController.ts
  src/main/controllers/EmployersContractClaimController.ts
  src/main/controllers/EmployersContractClaimDetailsController.ts
  src/main/controllers/HearingPreferencesController.ts
  src/main/controllers/IsClaimantEmploymentWithRespondentContinuingController.ts
  src/main/controllers/ReasonableAdjustmentsController.ts
  src/main/controllers/RespondentAddressController.ts
  src/main/controllers/RespondentContactPhoneNumberController.ts
  src/main/controllers/RespondentContactPreferencesController.ts
  src/main/controllers/RespondentContestClaimController.ts
  src/main/controllers/RespondentContestClaimReasonController.ts
  src/main/controllers/RespondentDXAddressController.ts
  src/main/controllers/RespondentEmployeesController.ts
  src/main/controllers/RespondentEnterAddressController.ts
  src/main/controllers/RespondentEnterPostCodeController.ts
  src/main/controllers/RespondentNameController.ts
  src/main/controllers/RespondentPreferredContactNameController.ts
  src/main/controllers/RespondentSelectPostCodeController.ts
  src/main/controllers/RespondentSiteEmployeesController.ts
  src/main/controllers/RespondentSitesController.ts
  src/main/controllers/TypeOfOrganisationController.ts
  src/main/definitions/radios.ts
  src/main/resources/locales/cy/translation/common.json
  src/main/resources/locales/en/translation/common.json
  src/test/unit/controllers/RespondentEnterPostCodeController.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-499
