Repository hmcts/et-syr-frontend, pull requests merged in 2025-05, with the labels that each got.

#685 fix dependency
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-syr-pr-685

#686 fix dependency
  yarn-audit-known-issues
Labels: ns:et, prd:et, rel:et-syr-pr-686

#678 RET-5767
  src/main/definitions/case.ts
  src/main/helpers/controller/ClaimantContactDetailsHelper.ts
  src/main/resources/locales/cy/translation/claimant-contact-details.json
  src/main/resources/locales/en/translation/claimant-contact-details.json
  src/test/unit/helpers/controller/ClaimantContactDetailsHelper.test.ts
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-678

#688 RET-5812
  src/main/resources/locales/cy/translation/home.json
  src/main/resources/locales/en/translation/home.json
  src/main/views/home.njk
Labels: ns:et, prd:et, enable_keep_helm, rel:et-syr-pr-688
